# market_data_agent/ingestion/kite_client.py

import os
from datetime import datetime
from typing import List, Union

from kiteconnect import KiteConnect
from dotenv import load_dotenv, find_dotenv

# REMOVED: No longer imports refresh_kite_access_token

class KiteDataClient:
    """
    A simple client that reads credentials from the environment and provides
    methods to interact with the Kite Connect API.

    It ASSUMES that a valid access token has already been generated by a
    separate, scheduled process (e.g., the daily 'refresh-token-daily' flow).
    """
    def __init__(self):
        # MODIFIED: The __init__ block is now much simpler.
        # It just loads the environment variables. No more Selenium.
        load_dotenv(find_dotenv(raise_error_if_not_found=True), override=True)

        self._api_key = os.getenv("KITE_API_KEY")
        self._access_token = os.getenv("KITE_ACCESS_TOKEN")

        if not self._api_key or not self._access_token:
            raise RuntimeError("KITE_API_KEY or KITE_ACCESS_TOKEN not found in .env. Has the refresh flow run?")

        self._kite = KiteConnect(api_key=self._api_key)
        self._kite.set_access_token(self._access_token)

        self._instrument_map = self._load_instruments("NSE")

    @property
    def api_key(self) -> str:
        """Exposes the API key for use by KiteTicker."""
        return self._api_key

    @property
    def access_token(self) -> str:
        """Exposes the access token for use by KiteTicker."""
        return self._access_token

    def _load_instruments(self, exchange: str) -> dict[str,int]:
        """
        Fetches and caches all instruments on given exchange.
        """
        insts = self._kite.instruments(exchange)
        return { row["tradingsymbol"]: row["instrument_token"] for row in insts }

    def get_instrument_token(self, symbol: str) -> int:
        """
        Returns the instrument_token required by Kite for any symbol.
        Raises if the symbol is unknown.
        """
        sym = symbol.replace(".NS","")
        try:
            return self._instrument_map[sym]
        except KeyError:
            raise ValueError(f"Unknown symbol: {symbol}")

    def fetch_ohlcv(
        self,
        symbols: Union[str,List[str]],
        from_date: Union[str,datetime],
        to_date:   Union[str,datetime],
        interval: str = "day"
    ) -> dict[str, List[dict]]:
        """
        Fetches OHLCV bars for one or more symbols.
        """
        if isinstance(symbols, str):
            symbols = [symbols]

        out = {}
        for sym in symbols:
            token = self.get_instrument_token(sym)
            data = self._kite.historical_data(
                instrument_token=token,
                from_date=self._parse_date(from_date),
                to_date=self._parse_date(to_date),
                interval=interval
            )
            out[sym] = data
        return out

    def fetch_ltp(self, symbols: Union[str,List[str]]) -> dict[str,float]:
        """
        Fetches the current Last Traded Price (LTP) for one or more symbols.
        """
        if isinstance(symbols, str):
            symbols = [symbols]
        keys = [f"NSE:{sym.replace('.NS','')}" for sym in symbols]
        data = self._kite.ltp(keys)
        return { sym: data[f"NSE:{sym.replace('.NS','')}"]["last_price"] for sym in symbols }

    @staticmethod
    def _parse_date(d: Union[str,datetime]) -> str:
        if isinstance(d, datetime):
            return d.strftime("%Y-%m-%d %H:%M:%S")
        return d