---
statement: pnl
nodes:
- id: statement_of_financial_results_by_banks_abstract
  extractable: false
  children:
  - id: date_of_start_of_reporting_period
    extractable: false
  - id: date_of_end_of_reporting_period
    extractable: false
  - id: whether_results_are_audited_or_unaudited
    extractable: false
  - id: nature_of_report_standalone_consolidated
    extractable: false
  - id: disclosure_of_operational_result_abstract
    extractable: false
    children:
    - id: disclosure_of_revenue_from_operations_abstract
      extractable: false
      children:
      - id: interest_earned_abstract
        extractable: false
        children:
        - id: interest_or_discount_on_advances_or_bills
        - id: revenue_on_investments
        - id: interest_on_balances_with_reserve_bank_of_india_and_other_inter_bank_funds
        - id: other_interest
        - id: interest_earned
      - id: other_income
      - id: income
    - id: expenses_abstract
      extractable: false
      children:
      - id: interest_expended
      - id: operating_expenses_abstract
        extractable: false
        children:
        - id: employees_cost
        - id: other_operating_expenses
        - id: operating_expenses
      - id: total_expenditure_excluding_provisions_and_contingencies
    - id: operating_profit_before_provision_and_contingencies
    - id: provisions_other_than_tax_and_contingencies
    - id: exceptional_items
    - id: net_profit_loss_from_ordinary_activities_before_tax
    - id: tax_expense
    - id: profit_loss_from_ordinary_activities_after_tax
    - id: extraordinary_items
    - id: net_profit_loss_for_the_period
    - id: share_of_profit_loss_of_associates
    - id: net_profit_loss_after_taxes_before_minority_interest
    - id: profit_loss_of_minority_interest
    - id: profit_loss_after_taxes_minority_interest_and_share_of_profit_loss_of_associates
  - id: details_of_paid_up_equity_share_capital_abstract
    extractable: false
    children:
    - id: paid_up_value_of_equity_share_capital
    - id: face_value_of_equity_share_capital
  - id: reserve_excluding_revaluation_reserves
  - id: analytical_ratios_abstract
    extractable: false
    children:
    - id: percentage_of_share_held_by_government_of_india
    - id: capital_adequacy_ratio_abstract
      extractable: false
      children:
      - id: cet1_ratio
      - id: additional_tier1_ratio
    - id: earnings_per_share_abstract
      extractable: false
      children:
      - id: earnings_per_share_before_extraordinary_items_abstract
        extractable: false
        children:
        - id: basic_earnings_per_share_before_extraordinary_items
        - id: diluted_earnings_per_share_before_extraordinary_items
      - id: earnings_per_share_after_extraordinary_items_abstract
        extractable: false
        children:
        - id: basic_earnings_per_share_after_extraordinary_items
        - id: diluted_earnings_per_share_after_extraordinary_items
    - id: npa_ratios_abstract
      extractable: false
      children:
      - id: gross_non_performing_assets
      - id: percentage_of_gross_npa
      - id: net_non_performing_assets
      - id: percentage_of_net_npa
    - id: return_on_assets
  - id: disclosure_of_notes_on_financial_results_explanatory_text_block
    extractable: false

---
statement: balance_sheet
nodes:
- id: statement_of_assets_and_liabilities_abstract
  extractable: false
  children:
  - id: capital_and_liabilities_abstract
    extractable: false
    children:
    - id: capital
    - id: reserves_and_surplus
    - id: deposits
    - id: borrowings
    - id: other_liabilities_and_provisions
    - id: total_capital_and_liabilities
    - id: policyholder_funds
  - id: assets_abstract
    extractable: false
    children:
    - id: cash_and_balances_with_reserve_bank_of_india
    - id: balances_with_banks_and_money_at_call_and_short_notice
    - id: investments
    - id: advances
    - id: fixed_assets
    - id: other_assets
    - id: total_assets
  - id: disclosure_of_notes_on_assets_and_liabilities_explanatory_text_block
    extractable: false
---
statement: cash_flow_indirect
nodes:
- id: statement_of_cash_flows_abstract
  extractable: false
  children:
  - id: cash_flows_from_used_in_operating_activities_abstract
    extractable: false
    children:
    - id: profit_before_tax
    - id: adjustments_for_reconcile_profit_loss_abstract
      extractable: false
      children:
      - id: adjustments_to_profit_loss_abstract
        extractable: false
        children:
        - id: adjustments_for_depreciation_and_amortisation_expense
        - id: profit_loss_on_revaluation_of_investments
        - id: amortisation_of_premium_on_investments
        - id: profit_loss_on_sale_of_fixed_assets
        - id: profit_loss_on_sale_of_subsidiaries
        - id: profit_loss_on_sale_of_investments
        - id: provision_for_non_performing_assets
        - id: provision_for_floating_provisions
        - id: provision_for_standard_assets_and_contingencies
        - id: dividend_income_from_subsidiaries
        - id: adjustments_for_sharebased_payments
        - id: other_adjustments_for_noncash_items
      - id: adjustments_for_working_capital_abstract
        extractable: false
        children:
        - id: adjustments_for_decrease_increase_in_advances
        - id: adjustments_for_increase_decrease_in_deposits
        - id: adjustments_for_decrease_increase_in_other_current_assets
        - id: adjustments_for_increase_decrease_in_other_current_liabilities
        - id: adjustments_for_decrease_increase_in_investments
    - id: interest_received_classified_as_operating_activities
    - id: interest_paid_classified_as_operating_activities
    - id: income_taxes_paid_refund_classified_as_operating_activities
    - id: net_cash_from_used_in_operating_activities
  - id: cash_flows_from_used_in_investing_activities_abstract
    extractable: false
    children:
    - id: purchase_of_tangible_assets_classified_as_investing_activities
    - id: proceeds_from_sale_of_tangible_assets_classified_as_investing_activities
    - id: purchase_of_investments_classified_as_investing_activities
    - id: proceeds_from_sale_of_investments_classified_as_investing_activities
    - id: dividends_received_classified_as_investing_activities
    - id: other_inflows_outflows_of_cash_classified_as_investing_activities
    - id: net_cash_from_used_in_investing_activities
  - id: cash_flows_from_used_in_financing_activities_abstract
    extractable: false
    children:
    - id: proceeds_from_issuing_shares
    - id: proceeds_from_issuing_other_equity_instruments
    - id: proceeds_from_issue_of_tier_1_and_tier_2_capital_instruments
    - id: redemption_of_tier_1_and_tier_2_capital_instruments
    - id: repayments_of_borrowings_classified_as_financing_activities
    - id: proceeds_from_borrowings_classified_as_financing_activities
    - id: dividends_paid_classified_as_financing_activities
    - id: other_inflows_outflows_of_cash_classified_as_financing_activities
    - id: net_cash_from_used_in_financing_activities
  - id: effect_of_exchange_rate_changes_on_cash_and_cash_equivalents
  - id: increase_decrease_in_cash_and_cash_equivalents
  - id: cash_and_cash_equivalents_at_beginning_of_period
  - id: cash_and_cash_equivalents_at_end_of_period
  - id: net_increase_decrease_in_cash_and_cash_equivalents_including_fx
    extractable: false
  - id: calc_cash_and_cash_equivalents_at_end_of_period
    extractable: false
  - id: cash_and_cash_equivalents_reconciliation_difference
    extractable: false
