-- ============================================================================
-- Migration: populate macro_data.tool_metadata HUMAN-CURATED fields for
--            ``calculate_real_yield_butterfly_tool`` (Phase 1, revamp
--            branch; brings the same-curve linker real-yield butterfly
--            primitive to lifecycle parity with breakeven_inflation_simple).
--
-- WHY THIS EXISTS
-- ---------------
-- The mechanical-field row for this tool already exists from the Phase-0
-- seed (database/migrations/2026-05-26_phase0_tool_metadata_seed.sql).
-- This migration fills in the three HUMAN-CURATED TEXT fields per the
-- per-tool lifecycle checklist Stage 3 (theoretical_reference,
-- known_limitations, desk_narrative).  source_material_verified stays
-- NULL — Stage 8 close-out is human sign-off per ADR 0015.
--
-- See:
--   - docs_revamped/03_standards/tool_lifecycle.md §2 axis 1/5/7
--   - docs_revamped/05_decisions/0015-tool-metadata-db-table.md
--
-- APPLY
-- -----
--   docker exec -i macro-tsdb psql -v ON_ERROR_STOP=1 -U quantuser -d macrodata \
--       < database/migrations/2026-05-29_phase1_calculate_real_yield_butterfly_curated.sql
-- ============================================================================

-- ----------------------------------------------------------------------------
-- UPSERT: idempotent.  Only the three human-curated TEXT fields move.
-- ----------------------------------------------------------------------------

UPDATE macro_data.tool_metadata
SET
    theoretical_reference = $tref$Tuckman & Serrat (2022), Fixed Income Securities: Tools for Today's Markets, 4th ed., Wiley, Ch. 22 (Inflation-Indexed Bonds) — textbook framing of the linker real-yield-to-maturity (Fisher decomposition: nominal yield ≈ real yield + expected inflation + inflation risk premium), with the real-yield curve treated as the desk-recognised view of ex-ante real rates after stripping inflation compensation. Tuckman 4e Ch. 8-10 (Yield Curves and Bootstrapping) — generic curve-shape framing applied here as a 3-point butterfly curvature on the linker real-yield curve. Fabozzi (ed.), Handbook of Fixed Income Securities, 9th ed., McGraw-Hill, Ch. 15-16 — standard fixed simple-butterfly weighting (-0.5, +1.0, -0.5) on (short, belly, long) as the canonical 3-point curvature primitive. Per-country primary issuer documentation for the linker curve families the primitive supports: US Treasury / TreasuryDirect (USD_TIPS — quarterly auctions, CPI-U seasonally-indexed); UK Debt Management Office (GBP_LINKER — index-linked Gilts; 3-month and 8-month lag; RPI → CPIH 2030 transition); Agence France Trésor (EUR_FR_LINKER — OATi/OATei, HICPxT reference); Bank of Canada (CAD_RRB — Real Return Bonds; legacy market, no new issuance since November 2022). The level-stat methodology (rolling 252-day z-score, period changes, trailing range) mirrors the sibling real_yield_level / real_yield_curve_spread / breakeven_butterfly tools; convention values are pinned by the cross-config lint per docs_revamped/03_standards/methodology_disclosure.md.$tref$,

    known_limitations = $klim$Same-country / same-curve-family invariant is load-bearing: all three endpoints share a single linker curve_family (USD_TIPS / GBP_LINKER / EUR_FR_LINKER / CAD_RRB). The input shape forbids cross-curve combinations; compute additionally re-asserts that the resolved instrument_master rows for that curve_family map to instrument_type='inflation_linker' AND a single (country, currency) tuple — a defensive guard against an instrument_master inconsistency, surfacing a controlled error envelope on mismatch rather than a silently averaged snapshot. The instrument_type discriminator (inflation_linker) is the load-bearing no-proxy guard at the underlying level primitive — passing a nominal sovereign curve_family at any endpoint surfaces the level primitive's controlled error envelope with the offending endpoint named. The fixed simple-butterfly weighting (-0.5, +1.0, -0.5) is a methodology choice locked in YAML — duration-neutral / DV01-weighted variants would ship as separate primitives (TD #planned_extensions). Three-tenor ordering (short_years < belly_years < long_years) is structural and rejected at the schema layer; the tool does NOT silently swap inverted tenors. Per-trade-date alignment uses a strict pandas inner-join across the three endpoint series AFTER each is computed independently — no synthetic butterfly points are produced on dates where ANY endpoint has no data (no ffill across the join). The butterfly stays in PERCENT (distinct from the BPS convention the sovereign butterfly uses, because real yields are NOT multiplied by 100); daily / weekly / monthly CHANGES are reported in BPS via period_changes(already_bps=False). The wire-frozen trailing_range_window_days (locked at 252 in V1; output field names high_252d_pct / low_252d_pct / percentile_252d embed the number) requires a schema migration + frontend update + parity-fixture regeneration to unlock. Per-curve grid limits: USD_TIPS exposes 5Y/10Y/20Y/30Y; GBP_LINKER exposes 1Y..50Y; EUR_FR_LINKER exposes 2Y/5Y/7Y/10Y/15Y; CAD_RRB exposes 5Y..30Y — a triplet must intersect the curve's ingested grid. Real-yield butterflies can be negative across stress windows (e.g. parts of post-2008 / 2020-21 when belly real yields were rich relative to a half-weighted wings average); the math is unchanged. Latest-observation cutoff anchors to the data's latest aligned trade_date (matching real_yield_level / real_yield_curve_spread / OIS rate_level) — linker daily series can lag wall-clock by several business days, so wall-clock anchoring would silently shrink the displayed window.$klim$,

    desk_narrative = $narr$Returns the current real-yield butterfly on a single sovereign linker curve — USD_TIPS 5s10s30s real-yield butterfly, GBP_LINKER 2s10s30s, EUR_FR_LINKER 2s10s15s, CAD_RRB 5s10s30s — together with daily / weekly / monthly bps changes, a rolling 252-day z-score against the series' own history, trailing 252-day high / low / percentile in PERCENT, the two component wing spreads (belly − short, long − belly), and the three endpoint real yields + year fractions so the curvature can be decomposed end-to-end without a second tool call. Computed pillar-by-pillar from linker real yields at three tenors, then weighted (-0.5, +1.0, -0.5) on (short, belly, long). Sign convention: POSITIVE = belly real yield is HIGH relative to the half-weighted wings (belly CHEAP); NEGATIVE = belly RICH. Same sign convention as the sovereign nominal butterfly and the sibling breakeven_butterfly so the four-tool family reads consistently. The canonical desk use is reading the SHAPE of real-rate term structure — i.e. the curvature of ex-ante real rates after stripping inflation compensation. A belly-rich move on a USD_TIPS 5s10s30s real-yield butterfly says the market is pricing higher real-rate compensation at the 10Y point than at the wings — typically a real-policy-tightening pricing read at intermediate horizons (the desk's "real-rate Fed pricing" curve-shape view). Pair with the matching breakeven_butterfly on the same curve to decompose a nominal sovereign butterfly: a moved nominal 5s10s30s butterfly is the sum of the real-yield butterfly and the breakeven butterfly, by construction. Output is in PERCENT (real yields are quoted in percent, not bps), with daily/weekly/monthly changes reported in bps per desk convention for rate-level changes. Caveat: this is the CURVATURE OF REAL YIELDS, distinct from a real-yield curve spread (2-point difference) and from the nominal sovereign butterfly (3-point curvature of nominal yields in bps); the same-curve invariant means a cross-country real-yield curvature comparison (USD_TIPS 2s10s30s vs GBP_LINKER 2s10s30s) is not expressible by this primitive's input shape and would be a different concept entirely.$narr$,

    updated_at = NOW()
WHERE tool_name = 'calculate_real_yield_butterfly_tool';

-- ----------------------------------------------------------------------------
-- Defensive INSERT fallback (Phase-0 seed not applied → row absent).
-- ----------------------------------------------------------------------------

INSERT INTO macro_data.tool_metadata (
    tool_name,
    domain,
    category,
    output_field_units,
    theoretical_reference,
    known_limitations,
    desk_narrative
)
SELECT
    'calculate_real_yield_butterfly_tool',
    'inflation_indexed_bonds',
    'cross_market_rv',
    '{"time_series_butterfly": "pct", "time_series_zscore": "z_score"}'::jsonb,
    $tref$Tuckman & Serrat (2022), Fixed Income Securities: Tools for Today's Markets, 4th ed., Wiley, Ch. 22 (Inflation-Indexed Bonds) — textbook framing of the linker real-yield-to-maturity (Fisher decomposition: nominal yield ≈ real yield + expected inflation + inflation risk premium), with the real-yield curve treated as the desk-recognised view of ex-ante real rates after stripping inflation compensation. Tuckman 4e Ch. 8-10 (Yield Curves and Bootstrapping) — generic curve-shape framing applied here as a 3-point butterfly curvature on the linker real-yield curve. Fabozzi (ed.), Handbook of Fixed Income Securities, 9th ed., McGraw-Hill, Ch. 15-16 — standard fixed simple-butterfly weighting (-0.5, +1.0, -0.5) on (short, belly, long) as the canonical 3-point curvature primitive. Per-country primary issuer documentation for the linker curve families the primitive supports: US Treasury / TreasuryDirect (USD_TIPS — quarterly auctions, CPI-U seasonally-indexed); UK Debt Management Office (GBP_LINKER — index-linked Gilts; 3-month and 8-month lag; RPI → CPIH 2030 transition); Agence France Trésor (EUR_FR_LINKER — OATi/OATei, HICPxT reference); Bank of Canada (CAD_RRB — Real Return Bonds; legacy market, no new issuance since November 2022). The level-stat methodology (rolling 252-day z-score, period changes, trailing range) mirrors the sibling real_yield_level / real_yield_curve_spread / breakeven_butterfly tools; convention values are pinned by the cross-config lint per docs_revamped/03_standards/methodology_disclosure.md.$tref$,
    $klim$Same-country / same-curve-family invariant is load-bearing: all three endpoints share a single linker curve_family (USD_TIPS / GBP_LINKER / EUR_FR_LINKER / CAD_RRB). The input shape forbids cross-curve combinations; compute additionally re-asserts that the resolved instrument_master rows for that curve_family map to instrument_type='inflation_linker' AND a single (country, currency) tuple — a defensive guard against an instrument_master inconsistency, surfacing a controlled error envelope on mismatch rather than a silently averaged snapshot. The instrument_type discriminator (inflation_linker) is the load-bearing no-proxy guard at the underlying level primitive — passing a nominal sovereign curve_family at any endpoint surfaces the level primitive's controlled error envelope with the offending endpoint named. The fixed simple-butterfly weighting (-0.5, +1.0, -0.5) is a methodology choice locked in YAML — duration-neutral / DV01-weighted variants would ship as separate primitives (TD #planned_extensions). Three-tenor ordering (short_years < belly_years < long_years) is structural and rejected at the schema layer; the tool does NOT silently swap inverted tenors. Per-trade-date alignment uses a strict pandas inner-join across the three endpoint series AFTER each is computed independently — no synthetic butterfly points are produced on dates where ANY endpoint has no data (no ffill across the join). The butterfly stays in PERCENT (distinct from the BPS convention the sovereign butterfly uses, because real yields are NOT multiplied by 100); daily / weekly / monthly CHANGES are reported in BPS via period_changes(already_bps=False). The wire-frozen trailing_range_window_days (locked at 252 in V1; output field names high_252d_pct / low_252d_pct / percentile_252d embed the number) requires a schema migration + frontend update + parity-fixture regeneration to unlock. Per-curve grid limits: USD_TIPS exposes 5Y/10Y/20Y/30Y; GBP_LINKER exposes 1Y..50Y; EUR_FR_LINKER exposes 2Y/5Y/7Y/10Y/15Y; CAD_RRB exposes 5Y..30Y — a triplet must intersect the curve's ingested grid. Real-yield butterflies can be negative across stress windows (e.g. parts of post-2008 / 2020-21 when belly real yields were rich relative to a half-weighted wings average); the math is unchanged. Latest-observation cutoff anchors to the data's latest aligned trade_date (matching real_yield_level / real_yield_curve_spread / OIS rate_level) — linker daily series can lag wall-clock by several business days, so wall-clock anchoring would silently shrink the displayed window.$klim$,
    $narr$Returns the current real-yield butterfly on a single sovereign linker curve — USD_TIPS 5s10s30s real-yield butterfly, GBP_LINKER 2s10s30s, EUR_FR_LINKER 2s10s15s, CAD_RRB 5s10s30s — together with daily / weekly / monthly bps changes, a rolling 252-day z-score against the series' own history, trailing 252-day high / low / percentile in PERCENT, the two component wing spreads (belly − short, long − belly), and the three endpoint real yields + year fractions so the curvature can be decomposed end-to-end without a second tool call. Computed pillar-by-pillar from linker real yields at three tenors, then weighted (-0.5, +1.0, -0.5) on (short, belly, long). Sign convention: POSITIVE = belly real yield is HIGH relative to the half-weighted wings (belly CHEAP); NEGATIVE = belly RICH. Same sign convention as the sovereign nominal butterfly and the sibling breakeven_butterfly so the four-tool family reads consistently. The canonical desk use is reading the SHAPE of real-rate term structure — i.e. the curvature of ex-ante real rates after stripping inflation compensation. A belly-rich move on a USD_TIPS 5s10s30s real-yield butterfly says the market is pricing higher real-rate compensation at the 10Y point than at the wings — typically a real-policy-tightening pricing read at intermediate horizons (the desk's "real-rate Fed pricing" curve-shape view). Pair with the matching breakeven_butterfly on the same curve to decompose a nominal sovereign butterfly: a moved nominal 5s10s30s butterfly is the sum of the real-yield butterfly and the breakeven butterfly, by construction. Output is in PERCENT (real yields are quoted in percent, not bps), with daily/weekly/monthly changes reported in bps per desk convention for rate-level changes. Caveat: this is the CURVATURE OF REAL YIELDS, distinct from a real-yield curve spread (2-point difference) and from the nominal sovereign butterfly (3-point curvature of nominal yields in bps); the same-curve invariant means a cross-country real-yield curvature comparison (USD_TIPS 2s10s30s vs GBP_LINKER 2s10s30s) is not expressible by this primitive's input shape and would be a different concept entirely.$narr$
WHERE NOT EXISTS (
    SELECT 1
    FROM macro_data.tool_metadata
    WHERE tool_name = 'calculate_real_yield_butterfly_tool'
);

-- ----------------------------------------------------------------------------
-- Stage 8 closeout (NOT applied here): set source_material_verified once a
-- human verifier signs off the references above.
-- ============================================================================
