-- ============================================================================
-- Migration: populate macro_data.tool_metadata HUMAN-CURATED fields for
--            ``scan_inflation_swaps_extremes_tool`` (Phase 1, revamp branch;
--            morning sweep across the ZCIS universe).
--
-- WHY THIS EXISTS
-- ---------------
-- The mechanical-field row for this tool already exists from the Phase-0
-- seed (database/migrations/2026-05-26_phase0_tool_metadata_seed.sql).
-- This migration fills in the three HUMAN-CURATED TEXT fields per the
-- per-tool lifecycle checklist Stage 3 (theoretical_reference,
-- known_limitations, desk_narrative).  source_material_verified stays
-- NULL — Stage 8 close-out is human sign-off per ADR 0015.
--
-- See:
--   - docs_revamped/03_standards/tool_lifecycle.md §2 axis 1/5/7
--   - docs_revamped/05_decisions/0015-tool-metadata-db-table.md
--
-- APPLY
-- -----
--   docker exec -i macro-tsdb psql -v ON_ERROR_STOP=1 -U quantuser -d macrodata \
--       < database/migrations/2026-05-29_phase1_scan_inflation_swaps_extremes_curated.sql
-- ============================================================================

-- ----------------------------------------------------------------------------
-- UPSERT: idempotent.  Only the three human-curated TEXT fields move.
-- ----------------------------------------------------------------------------

UPDATE macro_data.tool_metadata
SET
    theoretical_reference = $tref$Fabozzi & Mann (eds.), Handbook of Fixed Income Securities, 9th ed., McGraw-Hill, Ch. 50-51 (Inflation-Linked Derivatives and the Inflation Swap Market) — textbook framing of the ZCIS quoted-rate level as the market's required inflation compensation under a specific index family, with cross-curve comparability subject to index-family and market-structure caveats. Diebold & Rudebusch (2013), Yield Curve Modeling and Forecasting, Princeton University Press, Ch. 3-4 — statistical framing of rolling z-score level-extreme screens against own-history distributions, applicable to any rate series including inflation-derivatives par rates. ISDA 2006 Definitions, Inflation Derivatives Supplement (Annex) — canonical conventions for ZCIS index references and per-curve indexation lag / interpolation (USD_ZCIS: 3M lag, Daily interpolation, CPI-U NSA; EUR_ZCIS: 3M lag, Monthly, HICPxT; GBP_ZCIS: 2M lag, Monthly, RPI). Bloomberg Inflation Derivatives documentation (USSWIT, EUSWI, BPSWIT tickers) — per-pillar quoted-rate observation source (PX_MID Bloomberg mnemonic). Methodology guardrail per the primitive catalog (build_order 25, inflation_swaps__scan_inflation_swaps_extremes): "Methodology card must state the z-score lookback window explicitly" — honoured here via the verbatim per-row and per-response methodology_disclosure. The 252-day rolling z-score, ddof=1, 60-observation minimum, 1.5x calendar-day buffer multiplier mirror the sibling sovereign / OIS / linker / bond_futures scanners; convention values are pinned by the cross-config lint per docs_revamped/03_standards/methodology_disclosure.md.$tref$,

    known_limitations = $klim$INDEX-FAMILY MISMATCH (load-bearing): USD_ZCIS references US CPI-U NSA (CPURNSA Index), EUR_ZCIS references Eurozone HICP ex-tobacco (CPTFEMU Index), GBP_ZCIS references UK RPI (UKRPI Index). Ranking ZCIS-rate z-scores across this heterogeneity is a useful morning screen but a 2.5σ extreme on USD_ZCIS 10Y reads against a different underlying inflation-compensation distribution than a 2.5σ extreme on GBP_ZCIS 10Y; the desk reader MUST interpret the ranking under that caveat, and the per-row underlying_index field surfaces the exact Bloomberg index ticker the contract references. MARKET-STRUCTURE MISMATCH (load-bearing): ZCIS markets differ across currencies in index-publication lag (USD_ZCIS 3M / EUR_ZCIS 3M / GBP_ZCIS 2M), interpolation convention (USD Daily vs EUR/GBP Monthly), dealer-quote liquidity, and structural basis vs the bond-implied breakeven curve. A z-score extreme on one market may reflect liquidity / structural-basis moves rather than pure inflation-expectations divergence. SINGLE-METRIC RANKING by ZCIS rate LEVEL z-score per the catalog's literal wording (required_metrics: [yield_mid]); daily_change_bps and monthly_change_bps are surfaced as per-row snapshot context but are NOT separate rankings (multi-metric expansion would widen scope past the catalog entry). MORNING SCREEN, NOT a tactical trade signal — the scan answers "where is the ZCIS curve stretched today?" and surfaces extremes for further analysis via inflation_swap_curve_spread / inflation_swap_forward / inflation_swap_butterfly / cross_market_inflation_swap_spread / swap_breakeven_basis_simple. Closed-family whitelist: only USD_ZCIS / EUR_ZCIS / GBP_ZCIS are accepted (sourced from the inflation_swap_curve_families YAML convention); passing a nominal sovereign / linker / OIS / policy-futures curve_family is refused at schema-validation time with routing guidance. The fetch window is METHODOLOGY (z_score_window_days × z_score_buffer_multiplier = 252 × 1.5 = 378 calendar days) — NOT an LLM input; exposing it would be an input-schema overreach (PR8 / OPR8). top_n and min_abs_z_score are DISPLAY thresholds with YAML-owned defaults (default_top_n=5, default_min_abs_z_score=1.5) — they control which stems appear in the output, not which stems are scanned. Stems with fewer than z_score_min_periods (60) aligned observations are SKIPPED, never silently demoted to z=None. as_of_date BEYOND the universe's last observed trade_date returns the documented controlled-error envelope (no silent re-labelling of an unbounded ranking as a future-anchored read). security_name is NOT surfaced because the ZCIS universe's instrument_metadata_history.security_name is universally NULL on the current DB snapshot; the no-proxy substitute is vendor_ticker under its own name (NOT relabelled as security_name).$klim$,

    desk_narrative = $narr$Morning sweep across the zero-coupon inflation swap universe — ranks every (curve_family, tenor) ZCIS pillar in USD_ZCIS / EUR_ZCIS / GBP_ZCIS (scope-narrowable via curve_families) by absolute 252-day rolling z-score of the quoted ZCIS rate LEVEL, and returns the top-N extremes. Each result row carries the latest cleaned ZCIS rate in percent, 1-day and ~1-month bps changes for snapshot context, the ranking z-score, an EXTREME_HIGH / EXTREME_LOW signal derived from the z's sign, plus per-row reference columns (maturity_date, underlying_index, vendor_ticker) so the desk knows which contract ranked extreme and which inflation index it references. The canonical desk use is the morning "what moved overnight, and what's stretched?" screen — a USD_ZCIS 5Y showing z = +2.3 says the 5Y CPI-U swap rate is two-plus standard deviations above its trailing-year mean, flagging it for closer attention. The intent is RANKING, not tactical signalling: a 2σ extreme is a question to investigate (via the matching inflation_swap_curve_spread to see curve-shape context, inflation_swap_forward to read forward inflation pricing, or cross_market_inflation_swap_spread / swap_breakeven_basis_simple to cross-check the bond-implied side), NOT a trade. Two load-bearing caveats every consumer must internalise: (1) the three curve families reference DIFFERENT inflation indices (CPI-U vs HICPxT vs RPI), so ranking z-scores across the universe mixes distributions with different basket weights / energy exposure / shelter conventions; (2) the markets differ in index-publication lag (USD/EUR 3M, GBP 2M), interpolation convention (USD Daily vs EUR/GBP Monthly), and dealer-quote liquidity, so an extreme reading on one market can reflect structural / liquidity moves as much as inflation-expectation divergence. Both caveats surface verbatim on the per-row methodology_disclosure AND on the response-level disclosure, so a downstream relay cannot strip them. Tunable display thresholds: top_n (default 5) and min_abs_z_score (default 1.5σ) — both YAML-defaulted, both LLM-overridable per query.$narr$,

    updated_at = NOW()
WHERE tool_name = 'scan_inflation_swaps_extremes_tool';

-- ----------------------------------------------------------------------------
-- Defensive INSERT fallback (Phase-0 seed not applied → row absent).
-- ----------------------------------------------------------------------------

INSERT INTO macro_data.tool_metadata (
    tool_name,
    domain,
    category,
    output_field_units,
    theoretical_reference,
    known_limitations,
    desk_narrative
)
SELECT
    'scan_inflation_swaps_extremes_tool',
    'inflation_swaps',
    'scanner',
    '{}'::jsonb,
    $tref$Fabozzi & Mann (eds.), Handbook of Fixed Income Securities, 9th ed., McGraw-Hill, Ch. 50-51 (Inflation-Linked Derivatives and the Inflation Swap Market) — textbook framing of the ZCIS quoted-rate level as the market's required inflation compensation under a specific index family, with cross-curve comparability subject to index-family and market-structure caveats. Diebold & Rudebusch (2013), Yield Curve Modeling and Forecasting, Princeton University Press, Ch. 3-4 — statistical framing of rolling z-score level-extreme screens against own-history distributions, applicable to any rate series including inflation-derivatives par rates. ISDA 2006 Definitions, Inflation Derivatives Supplement (Annex) — canonical conventions for ZCIS index references and per-curve indexation lag / interpolation (USD_ZCIS: 3M lag, Daily interpolation, CPI-U NSA; EUR_ZCIS: 3M lag, Monthly, HICPxT; GBP_ZCIS: 2M lag, Monthly, RPI). Bloomberg Inflation Derivatives documentation (USSWIT, EUSWI, BPSWIT tickers) — per-pillar quoted-rate observation source (PX_MID Bloomberg mnemonic). Methodology guardrail per the primitive catalog (build_order 25, inflation_swaps__scan_inflation_swaps_extremes): "Methodology card must state the z-score lookback window explicitly" — honoured here via the verbatim per-row and per-response methodology_disclosure. The 252-day rolling z-score, ddof=1, 60-observation minimum, 1.5x calendar-day buffer multiplier mirror the sibling sovereign / OIS / linker / bond_futures scanners; convention values are pinned by the cross-config lint per docs_revamped/03_standards/methodology_disclosure.md.$tref$,
    $klim$INDEX-FAMILY MISMATCH (load-bearing): USD_ZCIS references US CPI-U NSA (CPURNSA Index), EUR_ZCIS references Eurozone HICP ex-tobacco (CPTFEMU Index), GBP_ZCIS references UK RPI (UKRPI Index). Ranking ZCIS-rate z-scores across this heterogeneity is a useful morning screen but a 2.5σ extreme on USD_ZCIS 10Y reads against a different underlying inflation-compensation distribution than a 2.5σ extreme on GBP_ZCIS 10Y; the desk reader MUST interpret the ranking under that caveat, and the per-row underlying_index field surfaces the exact Bloomberg index ticker the contract references. MARKET-STRUCTURE MISMATCH (load-bearing): ZCIS markets differ across currencies in index-publication lag (USD_ZCIS 3M / EUR_ZCIS 3M / GBP_ZCIS 2M), interpolation convention (USD Daily vs EUR/GBP Monthly), dealer-quote liquidity, and structural basis vs the bond-implied breakeven curve. A z-score extreme on one market may reflect liquidity / structural-basis moves rather than pure inflation-expectations divergence. SINGLE-METRIC RANKING by ZCIS rate LEVEL z-score per the catalog's literal wording (required_metrics: [yield_mid]); daily_change_bps and monthly_change_bps are surfaced as per-row snapshot context but are NOT separate rankings (multi-metric expansion would widen scope past the catalog entry). MORNING SCREEN, NOT a tactical trade signal — the scan answers "where is the ZCIS curve stretched today?" and surfaces extremes for further analysis via inflation_swap_curve_spread / inflation_swap_forward / inflation_swap_butterfly / cross_market_inflation_swap_spread / swap_breakeven_basis_simple. Closed-family whitelist: only USD_ZCIS / EUR_ZCIS / GBP_ZCIS are accepted (sourced from the inflation_swap_curve_families YAML convention); passing a nominal sovereign / linker / OIS / policy-futures curve_family is refused at schema-validation time with routing guidance. The fetch window is METHODOLOGY (z_score_window_days × z_score_buffer_multiplier = 252 × 1.5 = 378 calendar days) — NOT an LLM input; exposing it would be an input-schema overreach (PR8 / OPR8). top_n and min_abs_z_score are DISPLAY thresholds with YAML-owned defaults (default_top_n=5, default_min_abs_z_score=1.5) — they control which stems appear in the output, not which stems are scanned. Stems with fewer than z_score_min_periods (60) aligned observations are SKIPPED, never silently demoted to z=None. as_of_date BEYOND the universe's last observed trade_date returns the documented controlled-error envelope (no silent re-labelling of an unbounded ranking as a future-anchored read). security_name is NOT surfaced because the ZCIS universe's instrument_metadata_history.security_name is universally NULL on the current DB snapshot; the no-proxy substitute is vendor_ticker under its own name (NOT relabelled as security_name).$klim$,
    $narr$Morning sweep across the zero-coupon inflation swap universe — ranks every (curve_family, tenor) ZCIS pillar in USD_ZCIS / EUR_ZCIS / GBP_ZCIS (scope-narrowable via curve_families) by absolute 252-day rolling z-score of the quoted ZCIS rate LEVEL, and returns the top-N extremes. Each result row carries the latest cleaned ZCIS rate in percent, 1-day and ~1-month bps changes for snapshot context, the ranking z-score, an EXTREME_HIGH / EXTREME_LOW signal derived from the z's sign, plus per-row reference columns (maturity_date, underlying_index, vendor_ticker) so the desk knows which contract ranked extreme and which inflation index it references. The canonical desk use is the morning "what moved overnight, and what's stretched?" screen — a USD_ZCIS 5Y showing z = +2.3 says the 5Y CPI-U swap rate is two-plus standard deviations above its trailing-year mean, flagging it for closer attention. The intent is RANKING, not tactical signalling: a 2σ extreme is a question to investigate (via the matching inflation_swap_curve_spread to see curve-shape context, inflation_swap_forward to read forward inflation pricing, or cross_market_inflation_swap_spread / swap_breakeven_basis_simple to cross-check the bond-implied side), NOT a trade. Two load-bearing caveats every consumer must internalise: (1) the three curve families reference DIFFERENT inflation indices (CPI-U vs HICPxT vs RPI), so ranking z-scores across the universe mixes distributions with different basket weights / energy exposure / shelter conventions; (2) the markets differ in index-publication lag (USD/EUR 3M, GBP 2M), interpolation convention (USD Daily vs EUR/GBP Monthly), and dealer-quote liquidity, so an extreme reading on one market can reflect structural / liquidity moves as much as inflation-expectation divergence. Both caveats surface verbatim on the per-row methodology_disclosure AND on the response-level disclosure, so a downstream relay cannot strip them. Tunable display thresholds: top_n (default 5) and min_abs_z_score (default 1.5σ) — both YAML-defaulted, both LLM-overridable per query.$narr$
WHERE NOT EXISTS (
    SELECT 1
    FROM macro_data.tool_metadata
    WHERE tool_name = 'scan_inflation_swaps_extremes_tool'
);

-- ----------------------------------------------------------------------------
-- Stage 8 closeout (NOT applied here): set source_material_verified once a
-- human verifier signs off the references above.
-- ============================================================================
