-- ============================================================================
-- Migration: populate macro_data.tool_metadata HUMAN-CURATED fields for
--            ``calculate_ois_curve_spread_tool`` (Phase 1, revamp branch;
--            brings the OIS curve-spread primitive to lifecycle parity).
--
-- WHY THIS EXISTS
-- ---------------
-- The mechanical-field row for this tool already exists from the Phase-0
-- seed (database/migrations/2026-05-26_phase0_tool_metadata_seed.sql).
-- This migration fills in the three HUMAN-CURATED TEXT fields per the
-- per-tool lifecycle checklist Stage 3 (theoretical_reference,
-- known_limitations, desk_narrative).  source_material_verified stays
-- NULL — Stage 8 close-out is human sign-off per ADR 0015.
--
-- See:
--   - docs_revamped/03_standards/tool_lifecycle.md §2 axis 1/5/7
--   - docs_revamped/05_decisions/0015-tool-metadata-db-table.md
--
-- APPLY
-- -----
--   docker exec -i macro-tsdb psql -v ON_ERROR_STOP=1 -U quantuser -d macrodata \
--       < database/migrations/2026-05-29_phase1_calculate_ois_curve_spread_curated.sql
-- ============================================================================

-- ----------------------------------------------------------------------------
-- UPSERT: idempotent.  Only the three human-curated TEXT fields move.
-- ----------------------------------------------------------------------------

UPDATE macro_data.tool_metadata
SET
    theoretical_reference = $tref$Fabozzi & Mann (eds.), Handbook of Fixed Income Securities, 9th ed., McGraw-Hill, Ch. 47-48 (Overnight Index Swaps and the OIS Curve) — textbook framing of the OIS par-swap rate as the market's required fixed payment in exchange for the geometric-mean of daily overnight-index fixings (SOFR / ESTR / SONIA / TONA / AONIA / CORRA) over the swap tenor; the OIS curve spread between two tenors gives the term structure of expected-policy-path pricing net of small OIS-specific term premia. Tuckman 4e Ch. 8-10 (Yield Curves and Bootstrapping) — generic curve-spread framing the desk uses to read 2s10s, 5s30s, 3M2Y, etc., applied here to the OIS par-swap curve. ISDA 2006 Definitions, OIS Annex — canonical conventions for OIS rate fixing per currency, compounding convention, and quoted par-rate semantics. Primary central-bank documentation for the underlying overnight indices: Federal Reserve Bank of New York (SOFR — secured overnight financing rate, daily compounding); European Central Bank (ESTR); Bank of England (SONIA); Bank of Japan (TONA); Reserve Bank of Australia (AONIA); Bank of Canada (CORRA). Bloomberg OIS curve documentation (USOSFR, EUSWE, BPSO, JYSO, ADSO, CDSW tickers) — primary market source for the per-pillar PX_LAST observations. The level-stat methodology (rolling 252-day z-score, ffill across holiday gaps, anchor at latest data observation) mirrors the sibling OIS rate_level / butterfly / forward_rate / cross_market_spread / swap_spread tools; convention values are pinned by the cross-config lint per docs_revamped/03_standards/methodology_disclosure.md.$tref$,

    known_limitations = $klim$Same-curve construction only: both endpoints share a single OIS curve_family from the playbook universe (USD_SOFR_OIS / EUR_ESTR_OIS / GBP_SONIA_OIS / JPY_OIS / AUD_OIS / CAD_OIS). Cross-curve OIS spreads (e.g. USD_SOFR_OIS 5Y minus EUR_ESTR_OIS 5Y) belong to the sibling OIS cross_market_spread primitive — this tool does NOT silently accept them. Tenor ordering (short_tenor != long_tenor) is structural and rejected at the schema layer with a precise error. RAW OIS PAR-RATE SPACE: the arithmetic is performed on raw OIS par rates, NOT on a bond-equivalent yield, NOT on a fitted curve object, and NOT after any basis adjustment (no LIBOR-OIS basis subtraction, no convexity adjustment, no term-premium decomposition). The output is the raw par-curve term structure under the curve's overnight-index reference (SOFR for USD, etc.), interpretable as expected-policy-path slope only with the term-premium caveat in mind. OIS par swap rates are stored as percent in the source DB (e.g. 4.25 = 4.25%); spread output is in BPS via ×100 multiplier applied at compute time and rounded to spread_bps_round_decimals=2. Observation cutoff is anchored to the data's latest observation date (not date.today()), matching the legacy single-file OIS curve_spread tool and OIS cross_market_spread / forward_rate / butterfly — sovereign curve_spread anchors to date.today() and that inconsistency mirrors yield_levels vs rate_level; will be reconciled in a separate PR. Same-date matching after up-to-5d ffill across holiday gaps; sample standard deviation (ddof=1) for the rolling z-score; z-score window is fixed (252 trading days) regardless of the user's display lookback. The OIS short-end grid is dense (1W, 1M, 2M, 3M, 6M, 9M, 1Y, 2Y, 3Y); the long end carries the standard 2Y / 5Y / 10Y / 20Y / 30Y points. A tenor must be present on the curve_family in instrument_master at both endpoints. The Bloomberg field convention default_swap_rate_field=PX_LAST is named distinctly from the sovereign default_field_name=YLD_YTM_MID so the cross-config lint can compare each family separately — LLM/HTTP wrappers MUST translate their wire-level empty-string sentinel to None so the YAML default flows through.$klim$,

    desk_narrative = $narr$Returns the basis-point spread between two tenors on the same OIS curve — USD_SOFR_OIS 2s10s, EUR_ESTR_OIS 3M2Y, GBP_SONIA_OIS 5s30s, JPY 1s5s, AUD 2s10s, CAD 5s10s — together with the daily bps change, a rolling 252-day z-score against the series' own history, and each leg's latest par-swap rate so the slope can be decomposed without a second tool call. Computed as spread_bps = (long_tenor_rate − short_tenor_rate) × 100 on raw OIS par rates from the playbook universe, aligned per-trade-date with up-to-5d ffill across holiday gaps inside each leg, then differenced. Sign convention: POSITIVE = curve is UPWARD-SLOPING (long-end OIS rate above short-end — the standard term-premium-plus-expected-hikes regime); NEGATIVE = INVERTED (front-end OIS above back-end — typically a near-term-policy-tightening-followed-by-cuts pricing read). The canonical desk use is reading the SHAPE of the expected-policy-path curve: a steepening USD 2s10s OIS spread says the market is pricing the back-end policy path higher relative to the near-term, typically a "cuts done, hold steady, then maybe up" or a structural-term-premium-rising regime depending on the wider macro read. Pair with the matching sovereign curve_spread to see the swap-bond curve-shape basis (sovereign curve − OIS curve = the slope of the swap-spread curve, a read on government credit / convenience yield), and with the matching OIS butterfly to see whether the slope move is in the front-end half (driven by 2s5s) or the back-end half (driven by 5s10s). Pair with cross_market_spread to see how the same-tenor reads compare across G-7 OIS markets. RAW OIS PAR-RATE SPACE: the arithmetic stays in raw par-rate space — no bond-equivalent yield conversion, no LIBOR-OIS basis subtraction, no convexity or term-premium adjustment. This is the term structure of OIS par-swap rates under the curve's overnight-index reference (SOFR / ESTR / SONIA / etc.), useful as the desk's reference curve for cleaner-than-sovereign expected-policy-path slope — but read with the OIS-specific term premium caveat in mind (small but non-zero across longer tenors).$narr$,

    updated_at = NOW()
WHERE tool_name = 'calculate_ois_curve_spread_tool';

-- ----------------------------------------------------------------------------
-- Defensive INSERT fallback (Phase-0 seed not applied → row absent).
-- ----------------------------------------------------------------------------

INSERT INTO macro_data.tool_metadata (
    tool_name,
    domain,
    category,
    output_field_units,
    theoretical_reference,
    known_limitations,
    desk_narrative
)
SELECT
    'calculate_ois_curve_spread_tool',
    'ois',
    'cross_market_rv',
    '{"time_series_spread": "bps", "time_series_zscore": "z_score"}'::jsonb,
    $tref$Fabozzi & Mann (eds.), Handbook of Fixed Income Securities, 9th ed., McGraw-Hill, Ch. 47-48 (Overnight Index Swaps and the OIS Curve) — textbook framing of the OIS par-swap rate as the market's required fixed payment in exchange for the geometric-mean of daily overnight-index fixings (SOFR / ESTR / SONIA / TONA / AONIA / CORRA) over the swap tenor; the OIS curve spread between two tenors gives the term structure of expected-policy-path pricing net of small OIS-specific term premia. Tuckman 4e Ch. 8-10 (Yield Curves and Bootstrapping) — generic curve-spread framing the desk uses to read 2s10s, 5s30s, 3M2Y, etc., applied here to the OIS par-swap curve. ISDA 2006 Definitions, OIS Annex — canonical conventions for OIS rate fixing per currency, compounding convention, and quoted par-rate semantics. Primary central-bank documentation for the underlying overnight indices: Federal Reserve Bank of New York (SOFR — secured overnight financing rate, daily compounding); European Central Bank (ESTR); Bank of England (SONIA); Bank of Japan (TONA); Reserve Bank of Australia (AONIA); Bank of Canada (CORRA). Bloomberg OIS curve documentation (USOSFR, EUSWE, BPSO, JYSO, ADSO, CDSW tickers) — primary market source for the per-pillar PX_LAST observations. The level-stat methodology (rolling 252-day z-score, ffill across holiday gaps, anchor at latest data observation) mirrors the sibling OIS rate_level / butterfly / forward_rate / cross_market_spread / swap_spread tools; convention values are pinned by the cross-config lint per docs_revamped/03_standards/methodology_disclosure.md.$tref$,
    $klim$Same-curve construction only: both endpoints share a single OIS curve_family from the playbook universe (USD_SOFR_OIS / EUR_ESTR_OIS / GBP_SONIA_OIS / JPY_OIS / AUD_OIS / CAD_OIS). Cross-curve OIS spreads (e.g. USD_SOFR_OIS 5Y minus EUR_ESTR_OIS 5Y) belong to the sibling OIS cross_market_spread primitive — this tool does NOT silently accept them. Tenor ordering (short_tenor != long_tenor) is structural and rejected at the schema layer with a precise error. RAW OIS PAR-RATE SPACE: the arithmetic is performed on raw OIS par rates, NOT on a bond-equivalent yield, NOT on a fitted curve object, and NOT after any basis adjustment (no LIBOR-OIS basis subtraction, no convexity adjustment, no term-premium decomposition). The output is the raw par-curve term structure under the curve's overnight-index reference (SOFR for USD, etc.), interpretable as expected-policy-path slope only with the term-premium caveat in mind. OIS par swap rates are stored as percent in the source DB (e.g. 4.25 = 4.25%); spread output is in BPS via ×100 multiplier applied at compute time and rounded to spread_bps_round_decimals=2. Observation cutoff is anchored to the data's latest observation date (not date.today()), matching the legacy single-file OIS curve_spread tool and OIS cross_market_spread / forward_rate / butterfly — sovereign curve_spread anchors to date.today() and that inconsistency mirrors yield_levels vs rate_level; will be reconciled in a separate PR. Same-date matching after up-to-5d ffill across holiday gaps; sample standard deviation (ddof=1) for the rolling z-score; z-score window is fixed (252 trading days) regardless of the user's display lookback. The OIS short-end grid is dense (1W, 1M, 2M, 3M, 6M, 9M, 1Y, 2Y, 3Y); the long end carries the standard 2Y / 5Y / 10Y / 20Y / 30Y points. A tenor must be present on the curve_family in instrument_master at both endpoints. The Bloomberg field convention default_swap_rate_field=PX_LAST is named distinctly from the sovereign default_field_name=YLD_YTM_MID so the cross-config lint can compare each family separately — LLM/HTTP wrappers MUST translate their wire-level empty-string sentinel to None so the YAML default flows through.$klim$,
    $narr$Returns the basis-point spread between two tenors on the same OIS curve — USD_SOFR_OIS 2s10s, EUR_ESTR_OIS 3M2Y, GBP_SONIA_OIS 5s30s, JPY 1s5s, AUD 2s10s, CAD 5s10s — together with the daily bps change, a rolling 252-day z-score against the series' own history, and each leg's latest par-swap rate so the slope can be decomposed without a second tool call. Computed as spread_bps = (long_tenor_rate − short_tenor_rate) × 100 on raw OIS par rates from the playbook universe, aligned per-trade-date with up-to-5d ffill across holiday gaps inside each leg, then differenced. Sign convention: POSITIVE = curve is UPWARD-SLOPING (long-end OIS rate above short-end — the standard term-premium-plus-expected-hikes regime); NEGATIVE = INVERTED (front-end OIS above back-end — typically a near-term-policy-tightening-followed-by-cuts pricing read). The canonical desk use is reading the SHAPE of the expected-policy-path curve: a steepening USD 2s10s OIS spread says the market is pricing the back-end policy path higher relative to the near-term, typically a "cuts done, hold steady, then maybe up" or a structural-term-premium-rising regime depending on the wider macro read. Pair with the matching sovereign curve_spread to see the swap-bond curve-shape basis (sovereign curve − OIS curve = the slope of the swap-spread curve, a read on government credit / convenience yield), and with the matching OIS butterfly to see whether the slope move is in the front-end half (driven by 2s5s) or the back-end half (driven by 5s10s). Pair with cross_market_spread to see how the same-tenor reads compare across G-7 OIS markets. RAW OIS PAR-RATE SPACE: the arithmetic stays in raw par-rate space — no bond-equivalent yield conversion, no LIBOR-OIS basis subtraction, no convexity or term-premium adjustment. This is the term structure of OIS par-swap rates under the curve's overnight-index reference (SOFR / ESTR / SONIA / etc.), useful as the desk's reference curve for cleaner-than-sovereign expected-policy-path slope — but read with the OIS-specific term premium caveat in mind (small but non-zero across longer tenors).$narr$
WHERE NOT EXISTS (
    SELECT 1
    FROM macro_data.tool_metadata
    WHERE tool_name = 'calculate_ois_curve_spread_tool'
);

-- ----------------------------------------------------------------------------
-- Stage 8 closeout (NOT applied here): set source_material_verified once a
-- human verifier signs off the references above.
-- ============================================================================
