-- ============================================================================
-- Migration: populate macro_data.tool_metadata HUMAN-CURATED fields for
--            ``calculate_breakeven_curve_spread_tool`` (Phase 1, revamp
--            branch; brings the breakeven-curve-spread primitive to
--            lifecycle parity with breakeven_inflation_simple).
--
-- WHY THIS EXISTS
-- ---------------
-- The mechanical-field row for this tool already exists from the Phase-0
-- seed (database/migrations/2026-05-26_phase0_tool_metadata_seed.sql).
-- This migration fills in the three HUMAN-CURATED TEXT fields per the
-- per-tool lifecycle checklist Stage 3 (theoretical_reference,
-- known_limitations, desk_narrative).  source_material_verified stays
-- NULL — Stage 8 close-out is human sign-off per ADR 0015.
--
-- See:
--   - docs_revamped/03_standards/tool_lifecycle.md §2 axis 1/5/7
--   - docs_revamped/05_decisions/0015-tool-metadata-db-table.md
--
-- APPLY
-- -----
--   docker exec -i macro-tsdb psql -v ON_ERROR_STOP=1 -U quantuser -d macrodata \
--       < database/migrations/2026-05-29_phase1_calculate_breakeven_curve_spread_curated.sql
-- ============================================================================

-- ----------------------------------------------------------------------------
-- UPSERT: idempotent.  Only the three human-curated TEXT fields move.
-- ----------------------------------------------------------------------------

UPDATE macro_data.tool_metadata
SET
    theoretical_reference = $tref$Tuckman & Serrat (2022), Fixed Income Securities: Tools for Today's Markets, 4th ed., Wiley, Ch. 22 (Inflation-Indexed Bonds) — textbook framing of the bond-implied breakeven as nominal-minus-real and the standard decomposition breakeven = expected inflation + inflation risk premium − relative liquidity premium; this primitive applies that decomposition twice (at short_tenor and long_tenor) and reports the long − short DIFFERENCE as the term-structure object. Tuckman 4e Ch. 8-10 (Yield Curves and Bootstrapping) — generic curve-spread / curve-shape framing the desk uses to read 2s10s, 5s30s, etc., applied here to the inflation-compensation curve. Per-country primary issuer documentation for the matched nominal + linker pairs the primitive supports: US Treasury / TreasuryDirect (UST + USD_TIPS); UK Debt Management Office (UK_GILT + GBP_LINKER; 3-month and 8-month indexation lag; RPI → CPIH 2030 transition); Agence France Trésor (FR_OAT + EUR_FR_LINKER, HICPxT reference); Bank of Canada (CANADA_GOVT + CAD_RRB). The level-stat methodology (rolling 252-day z-score, period changes, trailing range) mirrors the sibling breakeven_inflation_simple / forward_breakeven_simple / breakeven_butterfly / real_yield_curve_spread tools; convention values are pinned by the cross-config lint per docs_revamped/03_standards/methodology_disclosure.md.$tref$,

    known_limitations = $klim$Returns the TERM STRUCTURE OF INFLATION COMPENSATION, not the term structure of pure expected inflation — each endpoint breakeven carries an inflation risk premium and a relative liquidity premium between the nominal sovereign and the linker, and the curve spread inherits both at each endpoint. Same-country invariant is load-bearing and inherited transitively from the spot breakeven primitive's ``_enforce_same_country_invariant`` guard: cross-country pairs (e.g. DE_BUND vs EUR_FR_LINKER — same currency, different country; or UK_GILT vs USD_TIPS — different currency) are refused at compute time with a controlled error envelope BEFORE any market-data SELECT fires. The instrument_type discriminators are hard-coded in the composed spot primitive (linker leg = inflation_linker; nominal leg = sovereign_benchmark) — passing two linkers or two nominals at either endpoint surfaces the spot primitive's controlled error envelope with the offending short/long endpoint attribution. Tenor ordering (short_years < long_years) is structural and rejected at the schema layer; the tool does NOT silently swap inverted tenors (a caller passing short=10Y, long=2Y gets a precise schema-layer error). Per-trade-date alignment uses a strict pandas inner-join across the two endpoint series AFTER each is computed independently — no synthetic spread points are produced on dates where ONE endpoint has no data (no ffill across the join). The wire-frozen trailing_range_window_days (locked at 252 in V1; output field names high_252d_bps / low_252d_bps / percentile_252d embed the number) requires a schema migration + frontend update + parity-fixture regeneration to unlock. UK linkers carry mixed 3-month / 8-month indexation lag; Canadian RRBs are a declining-liquidity legacy market (no issuance since November 2022); the UK RPI → CPIH transition in 2030 bifurcates the gilt curve, so historical z-scores spanning the transition mix two methodology regimes. Latest-observation cutoff anchors to the data's latest aligned trade_date (matching breakeven_inflation_simple / forward_breakeven_simple / OIS rate_level / real_yield_level), NOT date.today(). A cross-country term-structure differential would be a sovereign-credit / inflation-regime hybrid and ships as a separate primitive (cross_country_breakeven_spread_simple), NOT as a config knob.$klim$,

    desk_narrative = $narr$Returns the slope of the bond-implied breakeven curve between two tenors of the same nominal/linker pair — UST/USD_TIPS 2s10s, 5s30s, etc.; UK Gilt vs index-linked Gilt; French OAT vs OATei; Canadian government vs RRB — together with daily / weekly / monthly bps changes, a rolling 252-day z-score against the series' own history, trailing 252-day high / low / percentile in bps, and the two endpoint breakevens + year fractions used to form the spread so the slope can be decomposed without a second tool call. Computed pillar-by-pillar as breakeven_short = nominal_short − real_short and breakeven_long = nominal_long − real_long, then reported as spread = long − short. Sign convention: POSITIVE spread = breakeven curve is UPWARD-SLOPING (long-end inflation compensation higher than short-end); NEGATIVE = inverted (front-end higher inflation compensation than back-end — typically a near-term inflation-spike-pricing read). The canonical desk use is reading inflation-compensation term structure: a steepening 2s10s breakeven curve says the market is pricing higher inflation premia further out (a reflation / structural-inflation read); a flattening read says the front-end is catching up (a near-term shock pricing in). Pair with the matching real_yield_curve_spread on the same curve to decompose a nominal curve move: did the curve steepen because real yields steepened, or because inflation expectations steepened? Caveat: this is INFLATION-COMPENSATION TERM STRUCTURE, not the term structure of pure expected inflation — each endpoint breakeven carries an inflation risk premium and a relative liquidity premium between the nominal sovereign and the linker, and the curve spread inherits both. A 2s10s breakeven slope that steepens 20bps could be 10bps of expected-inflation slope and 10bps of risk-premium slope; the tool does not decompose them and the desk reader must keep that caveat in mind. The tool refuses cross-country pairs by construction — a US-nominal vs UK-linker term-structure differential is a sovereign-credit / inflation-regime hybrid, not a generic breakeven curve.$narr$,

    updated_at = NOW()
WHERE tool_name = 'calculate_breakeven_curve_spread_tool';

-- ----------------------------------------------------------------------------
-- Defensive INSERT fallback (Phase-0 seed not applied → row absent).
-- ----------------------------------------------------------------------------

INSERT INTO macro_data.tool_metadata (
    tool_name,
    domain,
    category,
    output_field_units,
    theoretical_reference,
    known_limitations,
    desk_narrative
)
SELECT
    'calculate_breakeven_curve_spread_tool',
    'inflation_indexed_bonds',
    'cross_market_rv',
    '{"time_series_spread": "bps", "time_series_zscore": "z_score"}'::jsonb,
    $tref$Tuckman & Serrat (2022), Fixed Income Securities: Tools for Today's Markets, 4th ed., Wiley, Ch. 22 (Inflation-Indexed Bonds) — textbook framing of the bond-implied breakeven as nominal-minus-real and the standard decomposition breakeven = expected inflation + inflation risk premium − relative liquidity premium; this primitive applies that decomposition twice (at short_tenor and long_tenor) and reports the long − short DIFFERENCE as the term-structure object. Tuckman 4e Ch. 8-10 (Yield Curves and Bootstrapping) — generic curve-spread / curve-shape framing the desk uses to read 2s10s, 5s30s, etc., applied here to the inflation-compensation curve. Per-country primary issuer documentation for the matched nominal + linker pairs the primitive supports: US Treasury / TreasuryDirect (UST + USD_TIPS); UK Debt Management Office (UK_GILT + GBP_LINKER; 3-month and 8-month indexation lag; RPI → CPIH 2030 transition); Agence France Trésor (FR_OAT + EUR_FR_LINKER, HICPxT reference); Bank of Canada (CANADA_GOVT + CAD_RRB). The level-stat methodology (rolling 252-day z-score, period changes, trailing range) mirrors the sibling breakeven_inflation_simple / forward_breakeven_simple / breakeven_butterfly / real_yield_curve_spread tools; convention values are pinned by the cross-config lint per docs_revamped/03_standards/methodology_disclosure.md.$tref$,
    $klim$Returns the TERM STRUCTURE OF INFLATION COMPENSATION, not the term structure of pure expected inflation — each endpoint breakeven carries an inflation risk premium and a relative liquidity premium between the nominal sovereign and the linker, and the curve spread inherits both at each endpoint. Same-country invariant is load-bearing and inherited transitively from the spot breakeven primitive's ``_enforce_same_country_invariant`` guard: cross-country pairs (e.g. DE_BUND vs EUR_FR_LINKER — same currency, different country; or UK_GILT vs USD_TIPS — different currency) are refused at compute time with a controlled error envelope BEFORE any market-data SELECT fires. The instrument_type discriminators are hard-coded in the composed spot primitive (linker leg = inflation_linker; nominal leg = sovereign_benchmark) — passing two linkers or two nominals at either endpoint surfaces the spot primitive's controlled error envelope with the offending short/long endpoint attribution. Tenor ordering (short_years < long_years) is structural and rejected at the schema layer; the tool does NOT silently swap inverted tenors (a caller passing short=10Y, long=2Y gets a precise schema-layer error). Per-trade-date alignment uses a strict pandas inner-join across the two endpoint series AFTER each is computed independently — no synthetic spread points are produced on dates where ONE endpoint has no data (no ffill across the join). The wire-frozen trailing_range_window_days (locked at 252 in V1; output field names high_252d_bps / low_252d_bps / percentile_252d embed the number) requires a schema migration + frontend update + parity-fixture regeneration to unlock. UK linkers carry mixed 3-month / 8-month indexation lag; Canadian RRBs are a declining-liquidity legacy market (no issuance since November 2022); the UK RPI → CPIH transition in 2030 bifurcates the gilt curve, so historical z-scores spanning the transition mix two methodology regimes. Latest-observation cutoff anchors to the data's latest aligned trade_date (matching breakeven_inflation_simple / forward_breakeven_simple / OIS rate_level / real_yield_level), NOT date.today(). A cross-country term-structure differential would be a sovereign-credit / inflation-regime hybrid and ships as a separate primitive (cross_country_breakeven_spread_simple), NOT as a config knob.$klim$,
    $narr$Returns the slope of the bond-implied breakeven curve between two tenors of the same nominal/linker pair — UST/USD_TIPS 2s10s, 5s30s, etc.; UK Gilt vs index-linked Gilt; French OAT vs OATei; Canadian government vs RRB — together with daily / weekly / monthly bps changes, a rolling 252-day z-score against the series' own history, trailing 252-day high / low / percentile in bps, and the two endpoint breakevens + year fractions used to form the spread so the slope can be decomposed without a second tool call. Computed pillar-by-pillar as breakeven_short = nominal_short − real_short and breakeven_long = nominal_long − real_long, then reported as spread = long − short. Sign convention: POSITIVE spread = breakeven curve is UPWARD-SLOPING (long-end inflation compensation higher than short-end); NEGATIVE = inverted (front-end higher inflation compensation than back-end — typically a near-term inflation-spike-pricing read). The canonical desk use is reading inflation-compensation term structure: a steepening 2s10s breakeven curve says the market is pricing higher inflation premia further out (a reflation / structural-inflation read); a flattening read says the front-end is catching up (a near-term shock pricing in). Pair with the matching real_yield_curve_spread on the same curve to decompose a nominal curve move: did the curve steepen because real yields steepened, or because inflation expectations steepened? Caveat: this is INFLATION-COMPENSATION TERM STRUCTURE, not the term structure of pure expected inflation — each endpoint breakeven carries an inflation risk premium and a relative liquidity premium between the nominal sovereign and the linker, and the curve spread inherits both. A 2s10s breakeven slope that steepens 20bps could be 10bps of expected-inflation slope and 10bps of risk-premium slope; the tool does not decompose them and the desk reader must keep that caveat in mind. The tool refuses cross-country pairs by construction — a US-nominal vs UK-linker term-structure differential is a sovereign-credit / inflation-regime hybrid, not a generic breakeven curve.$narr$
WHERE NOT EXISTS (
    SELECT 1
    FROM macro_data.tool_metadata
    WHERE tool_name = 'calculate_breakeven_curve_spread_tool'
);

-- ----------------------------------------------------------------------------
-- Stage 8 closeout (NOT applied here): set source_material_verified once a
-- human verifier signs off the references above.
-- ============================================================================
