-- ============================================================================
-- Migration: populate macro_data.tool_metadata HUMAN-CURATED fields for
--            ``calculate_inflation_swap_butterfly_tool`` (Phase 1, revamp
--            branch; brings the same-curve ZCIS butterfly primitive to
--            lifecycle parity).
--
-- WHY THIS EXISTS
-- ---------------
-- The mechanical-field row for this tool already exists from the Phase-0
-- seed (database/migrations/2026-05-26_phase0_tool_metadata_seed.sql).
-- This migration fills in the three HUMAN-CURATED TEXT fields per the
-- per-tool lifecycle checklist Stage 3 (theoretical_reference,
-- known_limitations, desk_narrative).  source_material_verified stays
-- NULL — Stage 8 close-out is human sign-off per ADR 0015.
--
-- See:
--   - docs_revamped/03_standards/tool_lifecycle.md §2 axis 1/5/7
--   - docs_revamped/05_decisions/0015-tool-metadata-db-table.md
--
-- APPLY
-- -----
--   docker exec -i macro-tsdb psql -v ON_ERROR_STOP=1 -U quantuser -d macrodata \
--       < database/migrations/2026-05-29_phase1_calculate_inflation_swap_butterfly_curated.sql
-- ============================================================================

-- ----------------------------------------------------------------------------
-- UPSERT: idempotent.  Only the three human-curated TEXT fields move.
-- ----------------------------------------------------------------------------

UPDATE macro_data.tool_metadata
SET
    theoretical_reference = $tref$Fabozzi & Mann (eds.), Handbook of Fixed Income Securities, 9th ed., McGraw-Hill, Ch. 50-51 (Inflation-Linked Derivatives and the Inflation Swap Market) — textbook framing of the zero-coupon inflation swap (ZCIS) as a derivative paying realised cumulative inflation against a quoted fixed par-rate at maturity, with each pillar treated as the market's required compensation for bearing inflation under THAT index family over the swap tenor; the 3-point butterfly on a single ZCIS curve gives the curvature of inflation-compensation across the curve. Tuckman 4e Ch. 8-10 (Yield Curves and Bootstrapping) — generic curve-shape framing applied here as a 3-point fixed simple-butterfly on the ZCIS curve. ISDA 2006 Definitions, Inflation Derivatives Supplement — canonical conventions for ZCIS index references, indexation lag, and Daily / Monthly interpolation per curve family. Bloomberg Inflation Derivatives documentation (USSWIT, EUSWI, BPSWIT tickers) — primary market source for the per-pillar quoted-rate observations. Per-index primary methodology documentation: US Bureau of Labor Statistics CPI-U (CPURNSA Index), Eurostat HICP ex-tobacco (CPTFEMU Index), UK Office for National Statistics RPI (UKRPI Index). The level-stat methodology (rolling 252-day z-score, period changes, trailing range, strict inner-join alignment) mirrors the sibling inflation_swap_rate_level / inflation_swap_curve_spread / inflation_swap_forward tools and the cross-family breakeven_butterfly / real_yield_butterfly / OIS butterfly primitives; convention values are pinned by the cross-config lint per docs_revamped/03_standards/methodology_disclosure.md.$tref$,

    known_limitations = $klim$Same-curve invariant is load-bearing: all three endpoints share a single ZCIS curve_family (USD_ZCIS / EUR_ZCIS / GBP_ZCIS). The input shape forbids cross-curve butterflies; compute additionally re-asserts that the three resolved endpoint reads share inflation_index_family, index_lag, interpolation, and underlying_index — a defensive guard against an instrument_master inconsistency, surfacing a controlled error envelope on mismatch rather than a silently averaged snapshot. The four-conjunct no-proxy guard at the underlying level primitive (instrument_type='inflation_swap' AND pricing_type='zero_coupon_breakeven' AND curve_family=? AND tenor=?) is the load-bearing identity check — passing a different instrument family at any endpoint surfaces the level primitive's controlled error envelope with the offending short/belly/long endpoint named. The fixed simple-butterfly weighting (-0.5, +1.0, -0.5) is a methodology choice locked in YAML — duration-neutral / DV01-weighted variants would ship as separate primitives (TD #planned_extensions). Three-tenor ordering (short_years < belly_years < long_years) is structural and rejected at the schema layer; the tool does NOT silently swap inverted tenors. Per-trade-date alignment uses a strict pandas inner-join across the three endpoint series AFTER each is computed independently — no synthetic butterfly points are produced on dates where ANY endpoint has no data (no ffill across the join). RAW-RATE-SPACE PROMISE: the butterfly arithmetic stays in raw ZCIS par-rate space — there is NO subtraction of a model-derived basis (e.g. swap-vs-linker breakeven basis), NO inflation-risk-premium adjustment, and NO routing through a fitted curve object. The output is INFLATION-COMPENSATION CURVATURE under that curve's index family, NOT pure-expected-inflation curvature — the wire-locked methodology_label surfaces this caveat verbatim. The butterfly is in BPS (consistent with the BPS output convention the inflation_swaps domain established via inflation_swap_curve_spread for curve-shape views); underlying ZCIS rates flow through in PERCENT. The wire-frozen trailing_range_window_days (locked at 252 in V1; output field names high_252d_bps / low_252d_bps / percentile_252d embed the number) requires a schema migration + frontend update + parity-fixture regeneration to unlock. Per-curve grid limits: 1Y / 2Y / 3Y / 5Y / 10Y / 20Y / 30Y on each of USD_ZCIS / EUR_ZCIS / GBP_ZCIS. Latest-observation cutoff anchors to the data's latest aligned trade_date (matching inflation_swap_rate_level / inflation_swap_curve_spread / OIS rate_level).$klim$,

    desk_narrative = $narr$Returns the current ZCIS butterfly on a single inflation-swap curve — USD_ZCIS 5s10s30s, EUR_ZCIS 2s5s10s, GBP_ZCIS 2s10s30s — together with daily / weekly / monthly bps changes, a rolling 252-day z-score against the series' own history, trailing 252-day high / low / percentile in bps, the two component wing spreads (belly − short, long − belly), the three endpoint ZCIS rates + year fractions, and the curve's reference metadata (inflation_index_family, index_lag, interpolation, underlying_index) so the curvature can be decomposed end-to-end without a second tool call. Computed pillar-by-pillar from raw ZCIS par rates at three tenors, weighted (-0.5, +1.0, -0.5) on (short, belly, long), then ×100 to convert to bps. Sign convention: POSITIVE = belly ZCIS rate is HIGH relative to the half-weighted wings (belly CHEAP); NEGATIVE = belly RICH. Same sign convention as the sovereign nominal / linker real-yield / breakeven butterflies so the desk reads consistently across the four-tool family. The canonical desk use is reading the SHAPE of inflation-compensation pricing on the derivatives side — distinct from the breakeven_butterfly view because ZCIS quotes a clean single-currency inflation-compensation curve without the nominal-vs-linker liquidity premium drag the bond-implied breakeven curve carries. A belly-rich move on a USD_ZCIS 5s10s30s says the market is pricing higher 10Y inflation compensation than the half-weighted wings — typically a structural-inflation-pricing read at intermediate horizons. Pair with the matching breakeven_butterfly on the same currency / country to see the swap-bond basis (ZCIS butterfly vs breakeven butterfly = the curvature of the inflation-swap-versus-linker-bond basis), and with cross_market_inflation_swap_spread to compare butterfly readings across markets at a chosen tenor. RAW-RATE-SPACE PROMISE: the arithmetic stays in raw ZCIS par-rate space — there is no subtraction of a model-derived basis, no inflation-risk-premium adjustment, and no fitted-curve routing. This is INFLATION-COMPENSATION CURVATURE under the curve's index family (CPI-U / HICPxT / RPI), not a clean expected-inflation curvature; the methodology_label surfaces this caveat on every snapshot so the curvature reading is interpretable under the right convention.$narr$,

    updated_at = NOW()
WHERE tool_name = 'calculate_inflation_swap_butterfly_tool';

-- ----------------------------------------------------------------------------
-- Defensive INSERT fallback (Phase-0 seed not applied → row absent).
-- ----------------------------------------------------------------------------

INSERT INTO macro_data.tool_metadata (
    tool_name,
    domain,
    category,
    output_field_units,
    theoretical_reference,
    known_limitations,
    desk_narrative
)
SELECT
    'calculate_inflation_swap_butterfly_tool',
    'inflation_swaps',
    'cross_market_rv',
    '{"time_series_butterfly": "bps", "time_series_zscore": "z_score"}'::jsonb,
    $tref$Fabozzi & Mann (eds.), Handbook of Fixed Income Securities, 9th ed., McGraw-Hill, Ch. 50-51 (Inflation-Linked Derivatives and the Inflation Swap Market) — textbook framing of the zero-coupon inflation swap (ZCIS) as a derivative paying realised cumulative inflation against a quoted fixed par-rate at maturity, with each pillar treated as the market's required compensation for bearing inflation under THAT index family over the swap tenor; the 3-point butterfly on a single ZCIS curve gives the curvature of inflation-compensation across the curve. Tuckman 4e Ch. 8-10 (Yield Curves and Bootstrapping) — generic curve-shape framing applied here as a 3-point fixed simple-butterfly on the ZCIS curve. ISDA 2006 Definitions, Inflation Derivatives Supplement — canonical conventions for ZCIS index references, indexation lag, and Daily / Monthly interpolation per curve family. Bloomberg Inflation Derivatives documentation (USSWIT, EUSWI, BPSWIT tickers) — primary market source for the per-pillar quoted-rate observations. Per-index primary methodology documentation: US Bureau of Labor Statistics CPI-U (CPURNSA Index), Eurostat HICP ex-tobacco (CPTFEMU Index), UK Office for National Statistics RPI (UKRPI Index). The level-stat methodology (rolling 252-day z-score, period changes, trailing range, strict inner-join alignment) mirrors the sibling inflation_swap_rate_level / inflation_swap_curve_spread / inflation_swap_forward tools and the cross-family breakeven_butterfly / real_yield_butterfly / OIS butterfly primitives; convention values are pinned by the cross-config lint per docs_revamped/03_standards/methodology_disclosure.md.$tref$,
    $klim$Same-curve invariant is load-bearing: all three endpoints share a single ZCIS curve_family (USD_ZCIS / EUR_ZCIS / GBP_ZCIS). The input shape forbids cross-curve butterflies; compute additionally re-asserts that the three resolved endpoint reads share inflation_index_family, index_lag, interpolation, and underlying_index — a defensive guard against an instrument_master inconsistency, surfacing a controlled error envelope on mismatch rather than a silently averaged snapshot. The four-conjunct no-proxy guard at the underlying level primitive (instrument_type='inflation_swap' AND pricing_type='zero_coupon_breakeven' AND curve_family=? AND tenor=?) is the load-bearing identity check — passing a different instrument family at any endpoint surfaces the level primitive's controlled error envelope with the offending short/belly/long endpoint named. The fixed simple-butterfly weighting (-0.5, +1.0, -0.5) is a methodology choice locked in YAML — duration-neutral / DV01-weighted variants would ship as separate primitives (TD #planned_extensions). Three-tenor ordering (short_years < belly_years < long_years) is structural and rejected at the schema layer; the tool does NOT silently swap inverted tenors. Per-trade-date alignment uses a strict pandas inner-join across the three endpoint series AFTER each is computed independently — no synthetic butterfly points are produced on dates where ANY endpoint has no data (no ffill across the join). RAW-RATE-SPACE PROMISE: the butterfly arithmetic stays in raw ZCIS par-rate space — there is NO subtraction of a model-derived basis (e.g. swap-vs-linker breakeven basis), NO inflation-risk-premium adjustment, and NO routing through a fitted curve object. The output is INFLATION-COMPENSATION CURVATURE under that curve's index family, NOT pure-expected-inflation curvature — the wire-locked methodology_label surfaces this caveat verbatim. The butterfly is in BPS (consistent with the BPS output convention the inflation_swaps domain established via inflation_swap_curve_spread for curve-shape views); underlying ZCIS rates flow through in PERCENT. The wire-frozen trailing_range_window_days (locked at 252 in V1; output field names high_252d_bps / low_252d_bps / percentile_252d embed the number) requires a schema migration + frontend update + parity-fixture regeneration to unlock. Per-curve grid limits: 1Y / 2Y / 3Y / 5Y / 10Y / 20Y / 30Y on each of USD_ZCIS / EUR_ZCIS / GBP_ZCIS. Latest-observation cutoff anchors to the data's latest aligned trade_date (matching inflation_swap_rate_level / inflation_swap_curve_spread / OIS rate_level).$klim$,
    $narr$Returns the current ZCIS butterfly on a single inflation-swap curve — USD_ZCIS 5s10s30s, EUR_ZCIS 2s5s10s, GBP_ZCIS 2s10s30s — together with daily / weekly / monthly bps changes, a rolling 252-day z-score against the series' own history, trailing 252-day high / low / percentile in bps, the two component wing spreads (belly − short, long − belly), the three endpoint ZCIS rates + year fractions, and the curve's reference metadata (inflation_index_family, index_lag, interpolation, underlying_index) so the curvature can be decomposed end-to-end without a second tool call. Computed pillar-by-pillar from raw ZCIS par rates at three tenors, weighted (-0.5, +1.0, -0.5) on (short, belly, long), then ×100 to convert to bps. Sign convention: POSITIVE = belly ZCIS rate is HIGH relative to the half-weighted wings (belly CHEAP); NEGATIVE = belly RICH. Same sign convention as the sovereign nominal / linker real-yield / breakeven butterflies so the desk reads consistently across the four-tool family. The canonical desk use is reading the SHAPE of inflation-compensation pricing on the derivatives side — distinct from the breakeven_butterfly view because ZCIS quotes a clean single-currency inflation-compensation curve without the nominal-vs-linker liquidity premium drag the bond-implied breakeven curve carries. A belly-rich move on a USD_ZCIS 5s10s30s says the market is pricing higher 10Y inflation compensation than the half-weighted wings — typically a structural-inflation-pricing read at intermediate horizons. Pair with the matching breakeven_butterfly on the same currency / country to see the swap-bond basis (ZCIS butterfly vs breakeven butterfly = the curvature of the inflation-swap-versus-linker-bond basis), and with cross_market_inflation_swap_spread to compare butterfly readings across markets at a chosen tenor. RAW-RATE-SPACE PROMISE: the arithmetic stays in raw ZCIS par-rate space — there is no subtraction of a model-derived basis, no inflation-risk-premium adjustment, and no fitted-curve routing. This is INFLATION-COMPENSATION CURVATURE under the curve's index family (CPI-U / HICPxT / RPI), not a clean expected-inflation curvature; the methodology_label surfaces this caveat on every snapshot so the curvature reading is interpretable under the right convention.$narr$
WHERE NOT EXISTS (
    SELECT 1
    FROM macro_data.tool_metadata
    WHERE tool_name = 'calculate_inflation_swap_butterfly_tool'
);

-- ----------------------------------------------------------------------------
-- Stage 8 closeout (NOT applied here): set source_material_verified once a
-- human verifier signs off the references above.
-- ============================================================================
