-- ============================================================================
-- Generated by database/populate_tool_metadata.py — DO NOT EDIT BY HAND.
-- Regenerate by re-running the script.
--
-- Phase 0 seed for macro_data.tool_metadata: populates mechanical
-- fields (tool_name, domain, category, output_field_units) for every
-- backend-shipped primitive.  Human-curated fields
-- (theoretical_reference, known_limitations, desk_narrative,
-- source_material_verified) stay NULL — they get filled per tool in
-- Phase 1.
--
-- ON CONFLICT (tool_name) DO UPDATE updates the four mechanical
-- columns + updated_at on every re-run, leaving human-curated values
-- untouched.  Safe to run any number of times.
--
-- APPLY:
--   docker exec -i macro-tsdb psql -U quantuser -d macrodata \
--       < database/migrations/2026-05-26_phase0_tool_metadata_seed.sql
-- ============================================================================


INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('build_linker_panel_tool', 'inflation_indexed_bonds', 'panels', '{"panel":"percent"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('build_policy_futures_strip_panel_tool', 'policy_futures', 'panels', '{"panel":"percent"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('build_sovereign_yield_panel_tool', 'sovereign_bonds', 'panel_assembly', '{"panel":"percent"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('build_zcis_panel_tool', 'inflation_swaps', 'panels', '{"panel":"percent"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('calculate_beta_adjusted_spread_tool', 'sovereign_bonds', 'rolling_analytics', '{"time_series_beta":"ratio","time_series_residual":"bps","time_series_residual_z_score":"z_score"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('calculate_breakeven_butterfly_tool', 'inflation_indexed_bonds', 'curve_shape', '{"time_series":"bps","time_series_butterfly":"bps","time_series_zscore":"z_score"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('calculate_breakeven_curve_spread_tool', 'inflation_indexed_bonds', 'curve_shape', '{"time_series":"bps","time_series_spread":"bps","time_series_zscore":"z_score"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('calculate_breakeven_inflation_simple_tool', 'inflation_indexed_bonds', 'cross_market_rv', '{"time_series":"bps","time_series_breakeven":"bps","time_series_zscore":"z_score"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('calculate_breakeven_inflation_tool', 'sovereign_bonds', 'cross_market_rv', '{"time_series_breakeven":"bps","time_series_zscore":"z_score"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('calculate_butterfly_tool', 'sovereign_bonds', 'curve_shape', '{}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('calculate_cpi_surprise_tool', 'inflation_swaps', 'economic_release_surprises', '{"time_series_surprise":"percent","time_series_zscore":"z_score"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('calculate_cross_country_breakeven_spread_simple_tool', 'inflation_indexed_bonds', 'cross_market_rv', '{"time_series":"bps","time_series_spread":"bps","time_series_zscore":"z_score"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('calculate_cross_country_real_yield_spread_simple_tool', 'inflation_indexed_bonds', 'cross_market_rv', '{"time_series":"percent","time_series_spread":"percent","time_series_zscore":"z_score"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('calculate_cross_market_inflation_swap_spread_tool', 'inflation_swaps', 'cross_market_rv', '{"time_series":"bps","time_series_spread":"bps","time_series_zscore":"z_score"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('calculate_cross_market_spread_tool', 'sovereign_bonds', 'cross_market_rv', '{"time_series":"bps","time_series_spread":"bps","time_series_zscore":"z_score"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('calculate_curve_spread_tool', 'sovereign_bonds', 'curve_shape', '{"time_series":"bps","time_series_spread":"bps","time_series_zscore":"z_score"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('calculate_forward_breakeven_simple_tool', 'inflation_indexed_bonds', 'forwards_classify', '{"time_series":"bps","time_series_forward":"bps","time_series_zscore":"z_score"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('calculate_half_life_tool', 'sovereign_bonds', 'model_fits', '{}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('calculate_inflation_swap_butterfly_tool', 'inflation_swaps', 'curve_shape', '{"time_series":"bps","time_series_butterfly":"bps","time_series_zscore":"z_score"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('calculate_inflation_swap_curve_spread_tool', 'inflation_swaps', 'curve_shape', '{"time_series":"bps","time_series_spread":"bps","time_series_zscore":"z_score"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('calculate_inflation_swap_forward_tool', 'inflation_swaps', 'forwards_classify', '{"time_series":"percent","time_series_forward":"percent","time_series_zscore":"z_score"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('calculate_inflation_swap_rate_level_tool', 'inflation_swaps', 'snapshots', '{"time_series":"percent"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('calculate_nfp_surprise_tool', 'sovereign_bonds', 'economic_release_surprises', '{"time_series_surprise":"count","time_series_zscore":"z_score"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('calculate_ois_butterfly_tool', 'ois', 'spreads', '{"time_series":"bps","time_series_butterfly":"bps","time_series_zscore":"z_score"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('calculate_ois_cross_market_spread_tool', 'ois', 'cross_market_rv', '{"time_series":"bps","time_series_spread":"bps","time_series_zscore":"z_score"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('calculate_ois_curve_spread_tool', 'ois', 'curve_shape', '{"time_series":"bps","time_series_spread":"bps","time_series_zscore":"z_score"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('calculate_ois_forward_rate_tool', 'ois', 'forwards_classify', '{"time_series_forward":"percent","time_series_zscore":"z_score"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('calculate_otr_ofr_spread_tool', 'sovereign_bonds', 'curve_shape', '{"time_series_spread":"bps","time_series_zscore":"z_score"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('calculate_pca_yield_curve_tool', 'sovereign_bonds', 'model_fits', '{"time_series_factors":"factor_level"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('calculate_real_yield_butterfly_tool', 'inflation_indexed_bonds', 'curve_shape', '{"time_series":"percent","time_series_butterfly":"percent","time_series_zscore":"z_score"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('calculate_real_yield_curve_spread_tool', 'inflation_indexed_bonds', 'curve_shape', '{"time_series":"percent","time_series_spread":"percent","time_series_zscore":"z_score"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('calculate_rolling_regression_tool', 'sovereign_bonds', 'rolling_analytics', '{"time_series_alpha":"percent","time_series_betas":"ratio","time_series_condition_flag":"count","time_series_r_squared":"ratio","time_series_residual":"percent"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('calculate_swap_breakeven_basis_simple_tool', 'inflation_swaps', 'cross_market_rv', '{"time_series":"bps","time_series_basis":"bps","time_series_zscore":"z_score"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('calculate_swap_spread_tool', 'ois', 'cross_market_rv', '{"time_series":"bps","time_series_change_zscore":"z_score","time_series_spread":"bps","time_series_zscore":"z_score"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('calculate_wirp_meeting_pricing_tool', 'ois', 'meeting_pricing', '{}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('calculate_yield_change_attribution_pca_tool', 'sovereign_bonds', 'model_fits', '{}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('calculate_zscore_custom_tool', 'sovereign_bonds', 'rolling_analytics', '{"time_series":"z_score","time_series_zscore":"z_score"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('classify_curve_move_tool', 'sovereign_bonds', 'forwards_classify', '{}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('compute_financing_rate_tool', 'ois', 'panel_assembly', '{"panel":"percent"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('get_futures_price_level_tool', 'bond_futures', 'snapshots', '{}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('get_futures_volume_oi_tool', 'bond_futures', 'snapshots', '{}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('get_ois_rate_level_tool', 'ois', 'snapshots', '{"time_series":"percent"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('get_otr_history_tool', 'sovereign_bonds', 'snapshots', '{}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('get_real_yield_level_tool', 'inflation_indexed_bonds', 'snapshots', '{"time_series":"percent"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('get_scan_policy_futures_extremes_tool', 'policy_futures', 'scanners', '{}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('get_yield_levels_tool', 'sovereign_bonds', 'snapshots', '{"time_series":"percent"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('policy_futures_get_futures_butterfly_simple_tool', 'policy_futures', 'spreads', '{"time_series":"percent","time_series_butterfly":"percent","time_series_zscore":"z_score"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('policy_futures_get_futures_calendar_spread_tool', 'policy_futures', 'spreads', '{}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('policy_futures_get_futures_cross_market_spread_tool', 'policy_futures', 'spreads', '{"time_series":"percent","time_series_spread":"percent","time_series_zscore":"z_score"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('policy_futures_get_futures_pack_average_simple_tool', 'policy_futures', 'aggregates', '{"time_series":"percent","time_series_pack_average":"percent","time_series_zscore":"z_score"}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('policy_futures_get_futures_price_level_tool', 'policy_futures', 'snapshots', '{}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('policy_futures_get_futures_strip_snapshot_tool', 'policy_futures', 'snapshots', '{}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('policy_futures_get_volume_open_interest_snapshot_tool', 'policy_futures', 'snapshots', '{}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('scan_bond_futures_extremes_tool', 'bond_futures', 'scanners', '{}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('scan_extremes_tool', 'sovereign_bonds', 'screening', '{}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('scan_inflation_linkers_extremes_tool', 'inflation_indexed_bonds', 'scanners', '{}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('scan_inflation_swaps_extremes_tool', 'inflation_swaps', 'scanners', '{}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();

INSERT INTO macro_data.tool_metadata
    (tool_name, domain, category, output_field_units)
VALUES ('scan_ois_extremes_tool', 'ois', 'screening', '{}'::jsonb)
ON CONFLICT (tool_name) DO UPDATE SET
    domain             = EXCLUDED.domain,
    category           = EXCLUDED.category,
    output_field_units = EXCLUDED.output_field_units,
    updated_at         = NOW();
