-- ============================================================================
-- Migration: populate macro_data.tool_metadata HUMAN-CURATED fields for
--            ``calculate_cross_market_inflation_swap_spread_tool`` (Phase 1,
--            revamp branch; first cross-market ZCIS primitive to reach
--            lifecycle parity).
--
-- WHY THIS EXISTS
-- ---------------
-- The mechanical-field row for this tool already exists from the Phase-0
-- seed (database/migrations/2026-05-26_phase0_tool_metadata_seed.sql).
-- This migration fills in the three HUMAN-CURATED TEXT fields per the
-- per-tool lifecycle checklist Stage 3 (theoretical_reference,
-- known_limitations, desk_narrative).  source_material_verified stays
-- NULL — Stage 8 close-out is human sign-off per ADR 0015.
--
-- See:
--   - docs_revamped/03_standards/tool_lifecycle.md §2 axis 1/5/7
--   - docs_revamped/05_decisions/0015-tool-metadata-db-table.md
--
-- APPLY
-- -----
--   docker exec -i macro-tsdb psql -v ON_ERROR_STOP=1 -U quantuser -d macrodata \
--       < database/migrations/2026-05-29_phase1_calculate_cross_market_inflation_swap_spread_curated.sql
-- ============================================================================

-- ----------------------------------------------------------------------------
-- UPSERT: idempotent.  Only the three human-curated TEXT fields move.
-- ----------------------------------------------------------------------------

UPDATE macro_data.tool_metadata
SET
    theoretical_reference = $tref$Fabozzi & Mann (eds.), Handbook of Fixed Income Securities, 9th ed., McGraw-Hill, Ch. 50-51 (Inflation-Linked Derivatives and the Inflation Swap Market) — textbook framing of the zero-coupon inflation swap (ZCIS) as a single-payment derivative paying the realised cumulative inflation of a headline index over the swap tenor against a fixed quoted par-rate, with the ZCIS rate interpreted as the market's required compensation for bearing inflation under THAT index family. ISDA 2006 Definitions, Inflation Derivatives Supplement (Annex) — canonical conventions for ZCIS index references, indexation lag (3M for USD CPI-U / EU HICPxT, 2M for UK RPI), and interpolation (Daily vs Monthly fixing convention). Bloomberg Inflation Derivatives documentation (USSWIT, EUSWI, BPSWIT tickers) — primary market source for the per-leg quoted-rate observations. Per-index primary methodology documentation: US Bureau of Labor Statistics CPI-U non-seasonally-adjusted index (CPURNSA Index), Eurostat HICP ex-tobacco (CPTFEMU Index), UK Office for National Statistics RPI (UKRPI Index). The level-stat methodology (rolling 252-day z-score, period changes, trailing range, strict inner-join alignment) mirrors the sibling inflation_swap_rate_level / inflation_swap_curve_spread / inflation_swap_forward tools; convention values are pinned by the cross-config lint per docs_revamped/03_standards/methodology_disclosure.md.$tref$,

    known_limitations = $klim$INDEX-FAMILY CAVEAT IS LOAD-BEARING: USD_ZCIS references US CPI-U non-seasonally-adjusted, EUR_ZCIS references Eurozone HICP ex-tobacco, GBP_ZCIS references UK RPI — three structurally different inflation indices with different basket weights, energy/food exposure, and methodology. The cross-market ZCIS spread captures BOTH inflation-expectation differentials AND structural index-family differences; it is NOT a clean expected-inflation divergence read. The index_families_match flag is False on every cross-market pair drawn from the V1 universe (USD_ZCIS / EUR_ZCIS / GBP_ZCIS each reference distinct indices), and the wire surfaces per-leg inflation_index_family / index_lag / interpolation / underlying_index so the desk reader can decompose the spread under the correct conventions. Cross-market invariant (leg_a_curve_family != leg_b_curve_family) is rejected at the schema layer — same-curve, two-tenor ZCIS spreads belong to the inflation_swap_curve_spread primitive and are refused here. Same-tenor invariant: a single tenor field is shared by both legs in V1; same-forward-window cross-market spreads (e.g. USD 5Y5Y vs EUR 5Y5Y) and cross-tenor cross-market spreads (USD 5Y vs EUR 10Y) are documented under planned_extensions but not exposed in V1. Indexation-lag and interpolation differences across markets mean per-leg rates are quoted against differently-dated index fixings (USD 3M lag / Daily, EUR 3M lag / Monthly, GBP 2M lag / Monthly); the spread mixes these conventions and the methodology disclosure surfaces this verbatim. The wire-frozen trailing_range_window_days (locked at 252 in V1; output field names high_252d_bps / low_252d_bps / percentile_252d embed the number) requires a schema migration + frontend update + parity-fixture regeneration to unlock. Cross-market_sign_convention is wire-frozen at leg_a_minus_leg_b (left minus right); any change would require a coordinated update to the SQL validator + the wire-disclosed methodology label. Latest-observation cutoff anchors to the data's latest aligned trade_date (matching inflation_swap_rate_level / inflation_swap_curve_spread / OIS rate_level), NOT date.today(). Per-trade-date alignment uses a strict pandas inner-join — no synthetic spread points on dates where one leg has no data after each level primitive's ffill window (ffill_limit_days=5 inside each leg, never across the join).$klim$,

    desk_narrative = $narr$Returns the same-tenor cross-market zero-coupon inflation swap spread between two ZCIS curve families — USD_ZCIS 5Y minus EUR_ZCIS 5Y, USD_ZCIS 10Y minus GBP_ZCIS 10Y, EUR_ZCIS 5Y minus GBP_ZCIS 5Y — together with daily / weekly / monthly bps changes, a rolling 252-day z-score against the series' own history, trailing 252-day high / low / percentile in bps, and each leg's reference metadata (inflation_index_family, index_lag, interpolation, underlying_index) so the spread can be interpreted under the correct index-family caveat without a second tool call. Computed leg-by-leg from each market's ZCIS par rate at the requested tenor, then differenced as leg_a − leg_b (left minus right — the sign is predictable from input ordering). Output carries both percent and bps representations; the canonical TimeSeries surface is in bps to align with the sovereign cross_market_spread convention. The canonical desk use is reading cross-market inflation-pricing divergences — the front-end question is "where is the market pricing higher inflation compensation, here or there?" A USD 5Y ZCIS minus EUR 5Y ZCIS that widens 30bps over a month says the market is pricing materially more 5Y inflation compensation in the US than in the eurozone — but with the LOAD-BEARING caveat that the two contracts reference DIFFERENT inflation indices (CPI-U vs HICPxT), so part of that 30bps is the structural CPI-U-vs-HICP gap (energy / shelter / owners-equivalent-rent differences) and only part is a true inflation-expectation divergence. Pair with the per-leg inflation_swap_rate_level tool on each market to see whether the move is being driven by one leg or both, and with cross_country_breakeven_spread_simple on the bond-implied side to confirm whether the inflation-swap-implied divergence is corroborated by bond-implied breakevens. Use as a cross-market RV screen, NOT as a clean expected-inflation differential — the index-family caveat surfaces inline on every response so the desk reader cannot misread the output.$narr$,

    updated_at = NOW()
WHERE tool_name = 'calculate_cross_market_inflation_swap_spread_tool';

-- ----------------------------------------------------------------------------
-- Defensive INSERT fallback (Phase-0 seed not applied → row absent).
-- ----------------------------------------------------------------------------

INSERT INTO macro_data.tool_metadata (
    tool_name,
    domain,
    category,
    output_field_units,
    theoretical_reference,
    known_limitations,
    desk_narrative
)
SELECT
    'calculate_cross_market_inflation_swap_spread_tool',
    'inflation_swaps',
    'cross_market_rv',
    '{"time_series_spread": "bps", "time_series_zscore": "z_score"}'::jsonb,
    $tref$Fabozzi & Mann (eds.), Handbook of Fixed Income Securities, 9th ed., McGraw-Hill, Ch. 50-51 (Inflation-Linked Derivatives and the Inflation Swap Market) — textbook framing of the zero-coupon inflation swap (ZCIS) as a single-payment derivative paying the realised cumulative inflation of a headline index over the swap tenor against a fixed quoted par-rate, with the ZCIS rate interpreted as the market's required compensation for bearing inflation under THAT index family. ISDA 2006 Definitions, Inflation Derivatives Supplement (Annex) — canonical conventions for ZCIS index references, indexation lag (3M for USD CPI-U / EU HICPxT, 2M for UK RPI), and interpolation (Daily vs Monthly fixing convention). Bloomberg Inflation Derivatives documentation (USSWIT, EUSWI, BPSWIT tickers) — primary market source for the per-leg quoted-rate observations. Per-index primary methodology documentation: US Bureau of Labor Statistics CPI-U non-seasonally-adjusted index (CPURNSA Index), Eurostat HICP ex-tobacco (CPTFEMU Index), UK Office for National Statistics RPI (UKRPI Index). The level-stat methodology (rolling 252-day z-score, period changes, trailing range, strict inner-join alignment) mirrors the sibling inflation_swap_rate_level / inflation_swap_curve_spread / inflation_swap_forward tools; convention values are pinned by the cross-config lint per docs_revamped/03_standards/methodology_disclosure.md.$tref$,
    $klim$INDEX-FAMILY CAVEAT IS LOAD-BEARING: USD_ZCIS references US CPI-U non-seasonally-adjusted, EUR_ZCIS references Eurozone HICP ex-tobacco, GBP_ZCIS references UK RPI — three structurally different inflation indices with different basket weights, energy/food exposure, and methodology. The cross-market ZCIS spread captures BOTH inflation-expectation differentials AND structural index-family differences; it is NOT a clean expected-inflation divergence read. The index_families_match flag is False on every cross-market pair drawn from the V1 universe (USD_ZCIS / EUR_ZCIS / GBP_ZCIS each reference distinct indices), and the wire surfaces per-leg inflation_index_family / index_lag / interpolation / underlying_index so the desk reader can decompose the spread under the correct conventions. Cross-market invariant (leg_a_curve_family != leg_b_curve_family) is rejected at the schema layer — same-curve, two-tenor ZCIS spreads belong to the inflation_swap_curve_spread primitive and are refused here. Same-tenor invariant: a single tenor field is shared by both legs in V1; same-forward-window cross-market spreads (e.g. USD 5Y5Y vs EUR 5Y5Y) and cross-tenor cross-market spreads (USD 5Y vs EUR 10Y) are documented under planned_extensions but not exposed in V1. Indexation-lag and interpolation differences across markets mean per-leg rates are quoted against differently-dated index fixings (USD 3M lag / Daily, EUR 3M lag / Monthly, GBP 2M lag / Monthly); the spread mixes these conventions and the methodology disclosure surfaces this verbatim. The wire-frozen trailing_range_window_days (locked at 252 in V1; output field names high_252d_bps / low_252d_bps / percentile_252d embed the number) requires a schema migration + frontend update + parity-fixture regeneration to unlock. Cross-market_sign_convention is wire-frozen at leg_a_minus_leg_b (left minus right); any change would require a coordinated update to the SQL validator + the wire-disclosed methodology label. Latest-observation cutoff anchors to the data's latest aligned trade_date (matching inflation_swap_rate_level / inflation_swap_curve_spread / OIS rate_level), NOT date.today(). Per-trade-date alignment uses a strict pandas inner-join — no synthetic spread points on dates where one leg has no data after each level primitive's ffill window (ffill_limit_days=5 inside each leg, never across the join).$klim$,
    $narr$Returns the same-tenor cross-market zero-coupon inflation swap spread between two ZCIS curve families — USD_ZCIS 5Y minus EUR_ZCIS 5Y, USD_ZCIS 10Y minus GBP_ZCIS 10Y, EUR_ZCIS 5Y minus GBP_ZCIS 5Y — together with daily / weekly / monthly bps changes, a rolling 252-day z-score against the series' own history, trailing 252-day high / low / percentile in bps, and each leg's reference metadata (inflation_index_family, index_lag, interpolation, underlying_index) so the spread can be interpreted under the correct index-family caveat without a second tool call. Computed leg-by-leg from each market's ZCIS par rate at the requested tenor, then differenced as leg_a − leg_b (left minus right — the sign is predictable from input ordering). Output carries both percent and bps representations; the canonical TimeSeries surface is in bps to align with the sovereign cross_market_spread convention. The canonical desk use is reading cross-market inflation-pricing divergences — the front-end question is "where is the market pricing higher inflation compensation, here or there?" A USD 5Y ZCIS minus EUR 5Y ZCIS that widens 30bps over a month says the market is pricing materially more 5Y inflation compensation in the US than in the eurozone — but with the LOAD-BEARING caveat that the two contracts reference DIFFERENT inflation indices (CPI-U vs HICPxT), so part of that 30bps is the structural CPI-U-vs-HICP gap (energy / shelter / owners-equivalent-rent differences) and only part is a true inflation-expectation divergence. Pair with the per-leg inflation_swap_rate_level tool on each market to see whether the move is being driven by one leg or both, and with cross_country_breakeven_spread_simple on the bond-implied side to confirm whether the inflation-swap-implied divergence is corroborated by bond-implied breakevens. Use as a cross-market RV screen, NOT as a clean expected-inflation differential — the index-family caveat surfaces inline on every response so the desk reader cannot misread the output.$narr$
WHERE NOT EXISTS (
    SELECT 1
    FROM macro_data.tool_metadata
    WHERE tool_name = 'calculate_cross_market_inflation_swap_spread_tool'
);

-- ----------------------------------------------------------------------------
-- Stage 8 closeout (NOT applied here): set source_material_verified once a
-- human verifier signs off the references above.
-- ============================================================================
