-- ============================================================================
-- Migration: populate macro_data.tool_metadata HUMAN-CURATED fields for
--            ``calculate_ois_butterfly_tool`` (Phase 1, revamp branch;
--            brings the same-curve OIS butterfly primitive to lifecycle
--            parity).
--
-- WHY THIS EXISTS
-- ---------------
-- The mechanical-field row for this tool already exists from the Phase-0
-- seed (database/migrations/2026-05-26_phase0_tool_metadata_seed.sql).
-- This migration fills in the three HUMAN-CURATED TEXT fields per the
-- per-tool lifecycle checklist Stage 3 (theoretical_reference,
-- known_limitations, desk_narrative).  source_material_verified stays
-- NULL — Stage 8 close-out is human sign-off per ADR 0015.
--
-- See:
--   - docs_revamped/03_standards/tool_lifecycle.md §2 axis 1/5/7
--   - docs_revamped/05_decisions/0015-tool-metadata-db-table.md
--
-- APPLY
-- -----
--   docker exec -i macro-tsdb psql -v ON_ERROR_STOP=1 -U quantuser -d macrodata \
--       < database/migrations/2026-05-29_phase1_calculate_ois_butterfly_curated.sql
-- ============================================================================

-- ----------------------------------------------------------------------------
-- UPSERT: idempotent.  Only the three human-curated TEXT fields move.
-- ----------------------------------------------------------------------------

UPDATE macro_data.tool_metadata
SET
    theoretical_reference = $tref$Fabozzi & Mann (eds.), Handbook of Fixed Income Securities, 9th ed., McGraw-Hill, Ch. 47-48 (Overnight Index Swaps and the OIS Curve) — textbook framing of the OIS par-swap rate as the market's required fixed payment in exchange for the geometric-mean of the daily overnight-index fixings over the swap tenor, with the OIS curve interpreted as the expected-policy-path curve net of small term premia. ISDA 2006 Definitions, OIS Annex — canonical conventions for OIS rate fixing (SOFR for USD, ESTR for EUR, SONIA for GBP, TONA for JPY, AONIA for AUD, CORRA for CAD), compounding convention, and quoted par-rate semantics. Tuckman 4e Ch. 8-10 (Yield Curves and Bootstrapping) — generic curve-shape framing applied here as a 3-point fixed simple-butterfly (-1, +2, -1 in raw rate space, doubled form ≡ -0.5, +1.0, -0.5 in half-wings form). Fabozzi (ed.), Handbook of Fixed Income Securities, 9th ed., Ch. 15-16 — standard butterfly weighting as the canonical 3-point curvature primitive on any rates curve. Primary issuer / central bank documentation for the underlying overnight index: Federal Reserve Bank of New York (SOFR); European Central Bank (ESTR); Bank of England (SONIA); Bank of Japan (TONA); Reserve Bank of Australia (AONIA); Bank of Canada (CORRA). Bloomberg OIS pages (USOSFR, EUSWE, BPSO, JYSO, ADSO, CDSW tickers) — primary market source for the per-pillar par-swap-rate observations (PX_LAST). The level-stat methodology (rolling 252-day z-score, period changes, trailing range) mirrors the sibling OIS rate_level / curve_spread / forward_rate / cross_market_spread / swap_spread tools; convention values are pinned by the cross-config lint per docs_revamped/03_standards/methodology_disclosure.md.$tref$,

    known_limitations = $klim$Same-curve invariant is structural: all three endpoints share a single OIS curve_family from a closed enum (USD_SOFR_OIS / EUR_ESTR_OIS / GBP_SONIA_OIS / JPY_OIS / AUD_OIS / CAD_OIS). Cross-curve butterflies (e.g. mixing USD_SOFR_OIS and EUR_ESTR_OIS pillars in a 3-point curvature) are forbidden at the input schema layer and would be a different primitive entirely (the cross-market_spread primitive already exists for two-curve same-tenor comparisons). The fixed simple-butterfly weighting (50-50 wings, weight tuple -1, +2, -1) is a methodology choice locked in YAML — DV01-neutral / duration-weighted / PCA-neutral variants are documented under planned_extensions and would ship as SEPARATE primitives (different concepts, not config knobs). Three-tenor ordering (short < belly < long) is structural and rejected at the schema layer; the tool does NOT silently swap inverted tenors. RAW OIS PAR-RATE SPACE: the arithmetic is performed on raw OIS par rates, NOT on a bond-equivalent yield, NOT on a fitted curve object, and NOT after any basis adjustment. No LIBOR / OIS basis subtraction, no convexity adjustment, no term-premium decomposition — the wire-locked methodology disclosure surfaces this so a downstream operator cannot misread the output as a cleaner expected-policy-path curvature. The wire-frozen trailing_range_window_days (locked at 252 in V1; output field names high_252d_bps / low_252d_bps / percentile_252d embed the number) requires a schema migration + frontend update + parity-fixture regeneration to unlock. Closed-enum gap: the primitive catalog's concept_summary references the longer overnight-index-suffixed labels (JPY_TONA_OIS / AUD_AONIA_OIS / CAD_CORRA_OIS); the playbook today uses the shorter form (JPY_OIS / AUD_OIS / CAD_OIS) and this primitive uses the playbook's actual names — adding the longer suffixes requires a paired edit to rates_agent/playbooks/ois.yml AND the CURVE_FAMILY_TO_CURRENCY mapping in swap_spread/schemas.py. Until those land the longer labels do not exist in the substrate and this primitive does not silently relabel them. OIS par swap rates are stored as percent in the source DB (e.g. 4.25 = 4.25%); butterfly output is in BPS (×100 multiplier applied at compute time). Daily change uses delta_bps with the bps_round_decimals convention threaded explicitly so the YAML is authoritative. Observation cutoff is anchored to the data's latest observation date (not date.today()), matching OIS curve_spread / cross_market_spread / forward_rate — the DB can be 1-3 days stale over weekends / holidays and wall-clock anchoring would produce inconsistent history.$klim$,

    desk_narrative = $narr$Returns the current OIS butterfly on a single overnight-index-swap curve — USD_SOFR_OIS 2s5s10s, EUR_ESTR_OIS 2s5s10s, GBP_SONIA_OIS 2s5s10s, and the equivalents on JPY / AUD / CAD — together with the daily bps change, a rolling 252-day z-score against the series' own history, trailing 252-day high / low / percentile in bps, the two component wing spreads (belly − short, long − belly), and each leg's latest par-swap rate in percent so the curvature can be decomposed without a second tool call. Computed pillar-by-pillar from raw OIS par rates at three tenors, weighted (-1, +2, -1) on (short, belly, long) in percent space, then ×100 to bps. Sign convention: POSITIVE = belly is CHEAP relative to the linear interpolation of the wings (belly OIS rate HIGH versus wings); NEGATIVE = belly RICH. Same sign convention as the sovereign nominal / linker real-yield / breakeven / inflation-swap butterflies — the desk reads consistently across the five-tool curvature family. The canonical desk use is reading the SHAPE of the expected-policy-path curve at intermediate horizons — a belly-rich move on a USD_SOFR_OIS 2s5s10s says the market is pricing the 5Y SOFR forward path lower than the linear interpolation of the 2Y and 10Y forwards, typically a near-term-cuts-then-rebound pricing read (the cuts-rates-then-flatten regime). Pair with the matching sovereign butterfly to see the swap-bond curvature basis (sovereign butterfly minus OIS butterfly = the curvature of the swap-spread curve, a credit / convenience-yield read on government paper), and with the calculate_ois_forward family to translate butterfly changes into forward-OIS-rate shifts at the belly pillar. RAW OIS PAR-RATE SPACE: the arithmetic stays in raw OIS par-rate space, in percent, before the ×100 BPS conversion — no bond-equivalent yield conversion, no LIBOR-OIS basis subtraction, no convexity adjustment, no term-premium decomposition. This is the curvature of the OIS par-swap curve, NOT a cleaner expected-policy-path curvature read; the methodology disclosure surfaces that caveat so a downstream operator cannot misread the output as DV01-neutral or as a term-premium-stripped object.$narr$,

    updated_at = NOW()
WHERE tool_name = 'calculate_ois_butterfly_tool';

-- ----------------------------------------------------------------------------
-- Defensive INSERT fallback (Phase-0 seed not applied → row absent).
-- ----------------------------------------------------------------------------

INSERT INTO macro_data.tool_metadata (
    tool_name,
    domain,
    category,
    output_field_units,
    theoretical_reference,
    known_limitations,
    desk_narrative
)
SELECT
    'calculate_ois_butterfly_tool',
    'ois',
    'cross_market_rv',
    '{"time_series_butterfly": "bps", "time_series_zscore": "z_score"}'::jsonb,
    $tref$Fabozzi & Mann (eds.), Handbook of Fixed Income Securities, 9th ed., McGraw-Hill, Ch. 47-48 (Overnight Index Swaps and the OIS Curve) — textbook framing of the OIS par-swap rate as the market's required fixed payment in exchange for the geometric-mean of the daily overnight-index fixings over the swap tenor, with the OIS curve interpreted as the expected-policy-path curve net of small term premia. ISDA 2006 Definitions, OIS Annex — canonical conventions for OIS rate fixing (SOFR for USD, ESTR for EUR, SONIA for GBP, TONA for JPY, AONIA for AUD, CORRA for CAD), compounding convention, and quoted par-rate semantics. Tuckman 4e Ch. 8-10 (Yield Curves and Bootstrapping) — generic curve-shape framing applied here as a 3-point fixed simple-butterfly (-1, +2, -1 in raw rate space, doubled form ≡ -0.5, +1.0, -0.5 in half-wings form). Fabozzi (ed.), Handbook of Fixed Income Securities, 9th ed., Ch. 15-16 — standard butterfly weighting as the canonical 3-point curvature primitive on any rates curve. Primary issuer / central bank documentation for the underlying overnight index: Federal Reserve Bank of New York (SOFR); European Central Bank (ESTR); Bank of England (SONIA); Bank of Japan (TONA); Reserve Bank of Australia (AONIA); Bank of Canada (CORRA). Bloomberg OIS pages (USOSFR, EUSWE, BPSO, JYSO, ADSO, CDSW tickers) — primary market source for the per-pillar par-swap-rate observations (PX_LAST). The level-stat methodology (rolling 252-day z-score, period changes, trailing range) mirrors the sibling OIS rate_level / curve_spread / forward_rate / cross_market_spread / swap_spread tools; convention values are pinned by the cross-config lint per docs_revamped/03_standards/methodology_disclosure.md.$tref$,
    $klim$Same-curve invariant is structural: all three endpoints share a single OIS curve_family from a closed enum (USD_SOFR_OIS / EUR_ESTR_OIS / GBP_SONIA_OIS / JPY_OIS / AUD_OIS / CAD_OIS). Cross-curve butterflies (e.g. mixing USD_SOFR_OIS and EUR_ESTR_OIS pillars in a 3-point curvature) are forbidden at the input schema layer and would be a different primitive entirely (the cross-market_spread primitive already exists for two-curve same-tenor comparisons). The fixed simple-butterfly weighting (50-50 wings, weight tuple -1, +2, -1) is a methodology choice locked in YAML — DV01-neutral / duration-weighted / PCA-neutral variants are documented under planned_extensions and would ship as SEPARATE primitives (different concepts, not config knobs). Three-tenor ordering (short < belly < long) is structural and rejected at the schema layer; the tool does NOT silently swap inverted tenors. RAW OIS PAR-RATE SPACE: the arithmetic is performed on raw OIS par rates, NOT on a bond-equivalent yield, NOT on a fitted curve object, and NOT after any basis adjustment. No LIBOR / OIS basis subtraction, no convexity adjustment, no term-premium decomposition — the wire-locked methodology disclosure surfaces this so a downstream operator cannot misread the output as a cleaner expected-policy-path curvature. The wire-frozen trailing_range_window_days (locked at 252 in V1; output field names high_252d_bps / low_252d_bps / percentile_252d embed the number) requires a schema migration + frontend update + parity-fixture regeneration to unlock. Closed-enum gap: the primitive catalog's concept_summary references the longer overnight-index-suffixed labels (JPY_TONA_OIS / AUD_AONIA_OIS / CAD_CORRA_OIS); the playbook today uses the shorter form (JPY_OIS / AUD_OIS / CAD_OIS) and this primitive uses the playbook's actual names — adding the longer suffixes requires a paired edit to rates_agent/playbooks/ois.yml AND the CURVE_FAMILY_TO_CURRENCY mapping in swap_spread/schemas.py. Until those land the longer labels do not exist in the substrate and this primitive does not silently relabel them. OIS par swap rates are stored as percent in the source DB (e.g. 4.25 = 4.25%); butterfly output is in BPS (×100 multiplier applied at compute time). Daily change uses delta_bps with the bps_round_decimals convention threaded explicitly so the YAML is authoritative. Observation cutoff is anchored to the data's latest observation date (not date.today()), matching OIS curve_spread / cross_market_spread / forward_rate — the DB can be 1-3 days stale over weekends / holidays and wall-clock anchoring would produce inconsistent history.$klim$,
    $narr$Returns the current OIS butterfly on a single overnight-index-swap curve — USD_SOFR_OIS 2s5s10s, EUR_ESTR_OIS 2s5s10s, GBP_SONIA_OIS 2s5s10s, and the equivalents on JPY / AUD / CAD — together with the daily bps change, a rolling 252-day z-score against the series' own history, trailing 252-day high / low / percentile in bps, the two component wing spreads (belly − short, long − belly), and each leg's latest par-swap rate in percent so the curvature can be decomposed without a second tool call. Computed pillar-by-pillar from raw OIS par rates at three tenors, weighted (-1, +2, -1) on (short, belly, long) in percent space, then ×100 to bps. Sign convention: POSITIVE = belly is CHEAP relative to the linear interpolation of the wings (belly OIS rate HIGH versus wings); NEGATIVE = belly RICH. Same sign convention as the sovereign nominal / linker real-yield / breakeven / inflation-swap butterflies — the desk reads consistently across the five-tool curvature family. The canonical desk use is reading the SHAPE of the expected-policy-path curve at intermediate horizons — a belly-rich move on a USD_SOFR_OIS 2s5s10s says the market is pricing the 5Y SOFR forward path lower than the linear interpolation of the 2Y and 10Y forwards, typically a near-term-cuts-then-rebound pricing read (the cuts-rates-then-flatten regime). Pair with the matching sovereign butterfly to see the swap-bond curvature basis (sovereign butterfly minus OIS butterfly = the curvature of the swap-spread curve, a credit / convenience-yield read on government paper), and with the calculate_ois_forward family to translate butterfly changes into forward-OIS-rate shifts at the belly pillar. RAW OIS PAR-RATE SPACE: the arithmetic stays in raw OIS par-rate space, in percent, before the ×100 BPS conversion — no bond-equivalent yield conversion, no LIBOR-OIS basis subtraction, no convexity adjustment, no term-premium decomposition. This is the curvature of the OIS par-swap curve, NOT a cleaner expected-policy-path curvature read; the methodology disclosure surfaces that caveat so a downstream operator cannot misread the output as DV01-neutral or as a term-premium-stripped object.$narr$
WHERE NOT EXISTS (
    SELECT 1
    FROM macro_data.tool_metadata
    WHERE tool_name = 'calculate_ois_butterfly_tool'
);

-- ----------------------------------------------------------------------------
-- Stage 8 closeout (NOT applied here): set source_material_verified once a
-- human verifier signs off the references above.
-- ============================================================================
