-- ============================================================================
-- Migration: populate macro_data.tool_metadata HUMAN-CURATED fields for
--            ``policy_futures_get_futures_price_level_tool`` (Phase 1,
--            revamp branch; brings the policy-futures strip-position
--            price-level monitor to lifecycle parity).
--
-- WHY THIS EXISTS
-- ---------------
-- The mechanical-field row for this tool already exists from the Phase-0
-- seed (database/migrations/2026-05-26_phase0_tool_metadata_seed.sql).
-- This migration fills in the three HUMAN-CURATED TEXT fields per the
-- per-tool lifecycle checklist Stage 3 (theoretical_reference,
-- known_limitations, desk_narrative).  source_material_verified stays
-- NULL — Stage 8 close-out is human sign-off per ADR 0015.
--
-- See:
--   - docs_revamped/03_standards/tool_lifecycle.md §2 axis 1/5/7
--   - docs_revamped/05_decisions/0015-tool-metadata-db-table.md
--   - docs_revamped/05_decisions/0013-futures-domain-agents.md (V1 scope)
--
-- APPLY
-- -----
--   docker exec -i macro-tsdb psql -v ON_ERROR_STOP=1 -U quantuser -d macrodata \
--       < database/migrations/2026-05-29_phase1_policy_futures_get_futures_price_level_curated.sql
-- ============================================================================

-- ----------------------------------------------------------------------------
-- UPSERT: idempotent.  Only the three human-curated TEXT fields move.
-- ----------------------------------------------------------------------------

UPDATE macro_data.tool_metadata
SET
    theoretical_reference = $tref$Hull (2022), Options, Futures, and Other Derivatives, 11th ed., Pearson, Ch. 6 (Interest Rate Futures) — textbook framing of short-term interest-rate (STIR) futures with the canonical 100-minus-rate inverse-pricing convention (price = 100 − implied rate), implied-rate decoding rules, contract specification (tick size, tick value, contract size), and quarterly serial-month contract structure. Fabozzi & Mann (eds.), Handbook of Fixed Income Securities, 9th ed., McGraw-Hill, Ch. 33 (Interest Rate Futures) — STIR strip framing (whites positions 1-4, reds positions 5-8) and the canonical rolling-generic strip-position convention the desk uses to read "front contract, front+1, front+2" without pinning to specific calendar months. Primary exchange documentation for the contract universe: CME Group SOFR Futures (SR1, SR3 — secured overnight financing rate; quarterly delivery; cash-settled to 3-month compounded SOFR at expiry; tick size 0.0025 / 0.005 depending on tenor); ICE Euribor Futures (ER — 3M Euribor IBOR fixing reference; quarterly delivery; cash-settled to the EBF Euribor fixing on the third Wednesday of the delivery month; tick size 0.005); ICE SONIA Futures (SFI — Bank of England SONIA, compounded daily over the reference period; cash-settled; tick size 0.005). ADR 0013 (docs_revamped/05_decisions/0013-futures-domain-agents.md) — V1 scope decision: this primitive ships the rolling-generic strip-position read; the CTD-of-futures-of-OIS mapping primitive is Phase-4 and out of V1 scope. The level-stat methodology (rolling 252-day z-score on the implied-rate level, ddof=1, 60-observation minimum, trailing 252-day range on BOTH price and implied-rate axes) mirrors the sibling sovereign yield_levels / OIS rate_level / bond_futures futures_price_level / real_yield_level / inflation_swap_rate_level tools; convention values are pinned by the cross-config lint per docs_revamped/03_standards/methodology_disclosure.md.$tref$,

    known_limitations = $klim$ROLLING-GENERIC STRIP READ AT strip_position N — NOT a CTD-of-futures-of-OIS curve (the CTD-implied-OIS mapping primitive is Phase-4 per ADR 0013 V1 scope and does not exist yet). The desk-recognised instrument identity is the STRIP SLOT (curve_family, strip_position), NOT a master contract stem or a calendar tenor — strip_position 1 is the front contract; higher positions are quarterly forwards down the strip. The inverse-pricing flag is sourced from instrument_master.attributes->>'inverse_pricing' (read by fetch_strip_position_reference) — NOT a hardcoded list in compute.py — keeping the methodology choice in metadata, not in code (PR8 / P6 no-hidden-methodology-choice). SOFR_FUT / SONIA_FUT / EUR_SHORT_RATE_FUT all carry inverse_pricing=true in V1, so implied_rate_pct = 100 − raw_price; a future direct-priced policy-futures family (e.g. TIIE_FUT) would flip the metadata flag without a code change. SHORT-RATE REGIME LABEL is METHODOLOGY DISCLOSURE (P5), NOT a load-bearing computation choice: SOFR / SONIA reference a compounded daily RFR (3-month look-back at expiry); Euribor (EUR_SHORT_RATE_FUT) references an unsecured 3M term IBOR. The methodology card surfaces the regime label inline so consumers cannot mistake one for the other; the short_rate_regime_map lives in YAML. The z-score lives on the IMPLIED-RATE axis (not the raw-price axis): for inverse-priced strips the two axes are monotone inversions, so z-scoring the raw price would flip the sign of every "extreme" reading relative to the rate — desks read the rate, the z follows the rate. Trailing range is reported on BOTH axes (high/low/mid in raw price AND in implied rate) but percentile is reported on the implied-rate axis only (the ranks are identical inversions for monotone inverse pricing). Wire-frozen trailing_range_window_days locked at 252 in V1 — the output field names high_252d_implied_rate_pct / low_252d_implied_rate_pct / mid_252d_implied_rate_pct / high_252d_raw_price / low_252d_raw_price / mid_252d_raw_price / percentile_252d embed the number; unlocking requires a schema migration + frontend update + parity-fixture regeneration. The bespoke time_series row shape (date, raw_price, implied_rate_pct) is intentional: each row carries TWO unit spaces side-by-side and shared.schemas.TimeSeriesUnits has no PRICE member in V1 (ADR-gated extension per P8). Daily change is raw subtraction in each unit space (NOT ×100 to bps; the implied-rate delta is in PERCENT POINTS). as_of_date beyond the universe's last observed trade_date returns the documented controlled-error envelope (no silent re-labelling of an unbounded read as a future-anchored read). Closed enum: strip_position is bounded 1..12 at the schema layer for headroom; the V1 playbook universe carries positions 1..8 (whites 1-4, reds 5-8). curve_family must be SOFR_FUT / SONIA_FUT / EUR_SHORT_RATE_FUT — bond_futures curve families route to the bond_futures agent.$klim$,

    desk_narrative = $narr$Returns the latest price and implied rate for ONE rolling-generic policy-futures strip slot (front contract, front+1, etc.) on ONE STIR curve — SOFR_FUT for the US Fed strip, EUR_SHORT_RATE_FUT for the ECB Euribor strip, SONIA_FUT for the BOE strip — together with daily changes in BOTH raw-price and implied-rate space, a rolling 252-day z-score of the implied-rate level, trailing 252-day high / low / mid on both axes plus the percentile rank of the current implied rate, observation count over the displayed window, and the as_of-bounded SCD2 disclosure block (underlying_contract_code, security_name, expiry_date, contract_size, tick_size, tick_value) so the desk knows which underlying contract the strip slot resolves to today. Computed by fetching the (curve_family, strip_position) price series, applying up-to-5d ffill across holiday gaps, deriving the implied rate via the metadata-driven inverse-pricing rule (implied_rate_pct = 100 − raw_price for the V1 inverse-priced universe), and computing 252-day z and range stats on the IMPLIED-RATE axis (the desk-recognised view). Sign convention on changes: positive daily_change_implied_rate_pct = implied rate moved UP (the strip is pricing tighter policy); positive daily_change_raw_price = price moved up (which for inverse-priced strips equals the implied rate moved DOWN — easier policy pricing). The two are mirror images by construction; both are surfaced so the desk reader can read in whichever space matches the neighbouring desk view. The canonical desk use is reading the strip's pricing of forward policy: SFR1 implied_rate_pct = 4.85% says the market is pricing 3-month compounded SOFR over the front-contract reference window at 4.85% — directly readable as a near-term Fed policy expectation. A z = +2 on SFR1 says the front-contract implied rate is two-plus standard deviations above its trailing-year mean — typically a Fed-hawkish-repricing read worth investigating. Pair with the matching futures_calendar_spread / futures_butterfly_simple / futures_pack_average_simple primitives to read curve shape across the strip, with futures_strip_snapshot to see all 8 strip slots in one view, and with scan_policy_futures_extremes for the morning sweep. Critical framing: this is a ROLLING-GENERIC STRIP READ at the requested position — NOT a CTD-of-futures-of-OIS curve (that primitive is Phase-4 per ADR 0013, not yet shipped). The methodology disclosure surfaces the strip-position scope, the per-strip RFR/IBOR regime label, the inverse-pricing rule, and the 252-day z-score lookback window verbatim on every response so consumers cannot strip the caveats when relaying the snapshot.$narr$,

    updated_at = NOW()
WHERE tool_name = 'policy_futures_get_futures_price_level_tool';

-- ----------------------------------------------------------------------------
-- Defensive INSERT fallback (Phase-0 seed not applied → row absent).
-- ----------------------------------------------------------------------------

INSERT INTO macro_data.tool_metadata (
    tool_name,
    domain,
    category,
    output_field_units,
    theoretical_reference,
    known_limitations,
    desk_narrative
)
SELECT
    'policy_futures_get_futures_price_level_tool',
    'policy_futures',
    'snapshot',
    '{}'::jsonb,
    $tref$Hull (2022), Options, Futures, and Other Derivatives, 11th ed., Pearson, Ch. 6 (Interest Rate Futures) — textbook framing of short-term interest-rate (STIR) futures with the canonical 100-minus-rate inverse-pricing convention (price = 100 − implied rate), implied-rate decoding rules, contract specification (tick size, tick value, contract size), and quarterly serial-month contract structure. Fabozzi & Mann (eds.), Handbook of Fixed Income Securities, 9th ed., McGraw-Hill, Ch. 33 (Interest Rate Futures) — STIR strip framing (whites positions 1-4, reds positions 5-8) and the canonical rolling-generic strip-position convention the desk uses to read "front contract, front+1, front+2" without pinning to specific calendar months. Primary exchange documentation for the contract universe: CME Group SOFR Futures (SR1, SR3 — secured overnight financing rate; quarterly delivery; cash-settled to 3-month compounded SOFR at expiry; tick size 0.0025 / 0.005 depending on tenor); ICE Euribor Futures (ER — 3M Euribor IBOR fixing reference; quarterly delivery; cash-settled to the EBF Euribor fixing on the third Wednesday of the delivery month; tick size 0.005); ICE SONIA Futures (SFI — Bank of England SONIA, compounded daily over the reference period; cash-settled; tick size 0.005). ADR 0013 (docs_revamped/05_decisions/0013-futures-domain-agents.md) — V1 scope decision: this primitive ships the rolling-generic strip-position read; the CTD-of-futures-of-OIS mapping primitive is Phase-4 and out of V1 scope. The level-stat methodology (rolling 252-day z-score on the implied-rate level, ddof=1, 60-observation minimum, trailing 252-day range on BOTH price and implied-rate axes) mirrors the sibling sovereign yield_levels / OIS rate_level / bond_futures futures_price_level / real_yield_level / inflation_swap_rate_level tools; convention values are pinned by the cross-config lint per docs_revamped/03_standards/methodology_disclosure.md.$tref$,
    $klim$ROLLING-GENERIC STRIP READ AT strip_position N — NOT a CTD-of-futures-of-OIS curve (the CTD-implied-OIS mapping primitive is Phase-4 per ADR 0013 V1 scope and does not exist yet). The desk-recognised instrument identity is the STRIP SLOT (curve_family, strip_position), NOT a master contract stem or a calendar tenor — strip_position 1 is the front contract; higher positions are quarterly forwards down the strip. The inverse-pricing flag is sourced from instrument_master.attributes->>'inverse_pricing' (read by fetch_strip_position_reference) — NOT a hardcoded list in compute.py — keeping the methodology choice in metadata, not in code (PR8 / P6 no-hidden-methodology-choice). SOFR_FUT / SONIA_FUT / EUR_SHORT_RATE_FUT all carry inverse_pricing=true in V1, so implied_rate_pct = 100 − raw_price; a future direct-priced policy-futures family (e.g. TIIE_FUT) would flip the metadata flag without a code change. SHORT-RATE REGIME LABEL is METHODOLOGY DISCLOSURE (P5), NOT a load-bearing computation choice: SOFR / SONIA reference a compounded daily RFR (3-month look-back at expiry); Euribor (EUR_SHORT_RATE_FUT) references an unsecured 3M term IBOR. The methodology card surfaces the regime label inline so consumers cannot mistake one for the other; the short_rate_regime_map lives in YAML. The z-score lives on the IMPLIED-RATE axis (not the raw-price axis): for inverse-priced strips the two axes are monotone inversions, so z-scoring the raw price would flip the sign of every "extreme" reading relative to the rate — desks read the rate, the z follows the rate. Trailing range is reported on BOTH axes (high/low/mid in raw price AND in implied rate) but percentile is reported on the implied-rate axis only (the ranks are identical inversions for monotone inverse pricing). Wire-frozen trailing_range_window_days locked at 252 in V1 — the output field names high_252d_implied_rate_pct / low_252d_implied_rate_pct / mid_252d_implied_rate_pct / high_252d_raw_price / low_252d_raw_price / mid_252d_raw_price / percentile_252d embed the number; unlocking requires a schema migration + frontend update + parity-fixture regeneration. The bespoke time_series row shape (date, raw_price, implied_rate_pct) is intentional: each row carries TWO unit spaces side-by-side and shared.schemas.TimeSeriesUnits has no PRICE member in V1 (ADR-gated extension per P8). Daily change is raw subtraction in each unit space (NOT ×100 to bps; the implied-rate delta is in PERCENT POINTS). as_of_date beyond the universe's last observed trade_date returns the documented controlled-error envelope (no silent re-labelling of an unbounded read as a future-anchored read). Closed enum: strip_position is bounded 1..12 at the schema layer for headroom; the V1 playbook universe carries positions 1..8 (whites 1-4, reds 5-8). curve_family must be SOFR_FUT / SONIA_FUT / EUR_SHORT_RATE_FUT — bond_futures curve families route to the bond_futures agent.$klim$,
    $narr$Returns the latest price and implied rate for ONE rolling-generic policy-futures strip slot (front contract, front+1, etc.) on ONE STIR curve — SOFR_FUT for the US Fed strip, EUR_SHORT_RATE_FUT for the ECB Euribor strip, SONIA_FUT for the BOE strip — together with daily changes in BOTH raw-price and implied-rate space, a rolling 252-day z-score of the implied-rate level, trailing 252-day high / low / mid on both axes plus the percentile rank of the current implied rate, observation count over the displayed window, and the as_of-bounded SCD2 disclosure block (underlying_contract_code, security_name, expiry_date, contract_size, tick_size, tick_value) so the desk knows which underlying contract the strip slot resolves to today. Computed by fetching the (curve_family, strip_position) price series, applying up-to-5d ffill across holiday gaps, deriving the implied rate via the metadata-driven inverse-pricing rule (implied_rate_pct = 100 − raw_price for the V1 inverse-priced universe), and computing 252-day z and range stats on the IMPLIED-RATE axis (the desk-recognised view). Sign convention on changes: positive daily_change_implied_rate_pct = implied rate moved UP (the strip is pricing tighter policy); positive daily_change_raw_price = price moved up (which for inverse-priced strips equals the implied rate moved DOWN — easier policy pricing). The two are mirror images by construction; both are surfaced so the desk reader can read in whichever space matches the neighbouring desk view. The canonical desk use is reading the strip's pricing of forward policy: SFR1 implied_rate_pct = 4.85% says the market is pricing 3-month compounded SOFR over the front-contract reference window at 4.85% — directly readable as a near-term Fed policy expectation. A z = +2 on SFR1 says the front-contract implied rate is two-plus standard deviations above its trailing-year mean — typically a Fed-hawkish-repricing read worth investigating. Pair with the matching futures_calendar_spread / futures_butterfly_simple / futures_pack_average_simple primitives to read curve shape across the strip, with futures_strip_snapshot to see all 8 strip slots in one view, and with scan_policy_futures_extremes for the morning sweep. Critical framing: this is a ROLLING-GENERIC STRIP READ at the requested position — NOT a CTD-of-futures-of-OIS curve (that primitive is Phase-4 per ADR 0013, not yet shipped). The methodology disclosure surfaces the strip-position scope, the per-strip RFR/IBOR regime label, the inverse-pricing rule, and the 252-day z-score lookback window verbatim on every response so consumers cannot strip the caveats when relaying the snapshot.$narr$
WHERE NOT EXISTS (
    SELECT 1
    FROM macro_data.tool_metadata
    WHERE tool_name = 'policy_futures_get_futures_price_level_tool'
);

-- ----------------------------------------------------------------------------
-- Stage 8 closeout (NOT applied here): set source_material_verified once a
-- human verifier signs off the references above.
-- ============================================================================
