name: quant-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pyarrow
  - pandas
  - sqlalchemy
  - psycopg2
  - selenium
  - python-dotenv
  - prefect
  - requests
  - pip
  - pip:
    - kiteconnect
    - watchdog
    - zope.interface
    - pyotp