name: macro-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pyarrow
  - pandas
  - scipy
  - sqlalchemy
  - psycopg
  - psycopg2-binary
  - python-dotenv
  - prefect>=3.0
  - requests
  - streamlit
  - pip
  - pip:
    - anthropic
    - pyyaml
    - google-cloud-storage
    - mcp
    - langchain-anthropic
    - langchain-mcp-adapters
    - langgraph